### ISSUE TITLE
Run babel for typescript before importing

### ISSUE THREAD

**Issue by JakubKoralewski** [martpie/next-transpile-modules#109]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**
Local.

**Describe the bug**
I'm using `babel-plugin-const-enum` to transpile const enums to const objects.

My .babelrc
```json
{
  "presets": [
    "@babel/preset-typescript",
      "next/babel"
  ],
  "plugins": [
    [
      "const-enum",
      {
        "transform": "constObject"
      }
    ]
  ]
}
```

**To Reproduce**

**Expected behavior**
The issue would be solved if babel transformed the input of the module

**Setup**

- Next.js version: 9.4.4
- `next-transpile-modules` version: 4.1.0
- Node.js version:14.5
- `npm`/`yarn` version: yarn 1.22.4
- Operating System: win
- Webpack 4 or 5: idk

**Additional context**
yarn workspaces setup with lerna

**Comment by JakubKoralewski** [comment]
I had a `.babelrc`. Using `babel.config.json` helped.

Reading the FAQ actually helps 🤣

**Comment by martpie** [comment]
I should add a second checkbox: `I WILL GIVE 100$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ`
