### ISSUE TITLE
Serverless support

### ISSUE THREAD

**Issue by martpie** [martpie/next-transpile-modules#11]
See a detailed explanation + repro here: https://github.com/martpie/next-plugin-transpile-modules/issues/8#issuecomment-459109258

**Comment by martpie** [comment]
Next.js 8 released. This becomes urgent.

**Comment by tsirlucas** [comment]
Update: Tried this again after some months and still having exactly the same problem with `next@8.1.0` and `next-transpile-modules@2.3.1`
