### ISSUE TITLE
Webpack 5 HMR does not work 

### ISSUE THREAD

**Issue by ScriptedAlchemy** [martpie/next-transpile-modules#112]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ

**Are you trying to transpile a local package or an npm package?**
If an npm package, which one?
Local Package
**Describe the bug**
A clear and concise description of what the bug is (don't forget the logs if applicable).

It seems that watchOptions isn't doing what it should be, HMR only works if I change something in the next.js directory (pages or whatever) but HMR is not activated when editing a transpiled module.

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):
Create a package that's transpiled, start in dev mode, make a change to the transpiled package, notice webpack doesn't trigger any build. 

**Expected behavior**

Edited packages should hot reload

**Setup**

- Next.js version: 9.5.2
- `next-transpile-modules` version: 4.x
- Node.js version: 12.13
- `npm`/`yarn` version: 1.16
- Operating System: OSX
- Webpack 4 or 5: 5

**Additional context**

**Comment by ScriptedAlchemy** [comment]
If i change the following, webpack will compile, but pages still do no actually hot reload updates, page refreshes also do not reflect the newly changed code. 

```js
        const ignored = isWebpack5
          ? config.watchOptions.ignored.concat(transpileModules.map(i=>('!**/node_modules/' + i +'/*').filter(i=>i != '**/node_modules/**')))
          : config.watchOptions.ignored
              .filter((pattern) => !regexEqual(pattern, /[\\/]node_modules[\\/]/) && pattern !== '**/node_modules/**')
              .concat(excludes);
        config.watchOptions.ignored = ignored;
        
```

**Comment by ScriptedAlchemy** [comment]
@martpie any ideas on this one?

**Comment by martpie** [comment]
I did not investigate it yet :c

**Comment by ScriptedAlchemy** [comment]
@martpie i found the problem. its this ignore options AND the new webpack 5 cache

`config.cache = false` makes it work, however my globs still are not right. 

Do you know how I could write a glob that excludes files

Something like `**/node_modules**/[!@lululemon]*`

**Comment by martpie** [comment]
I will tackle this for #132. How the code works has been quite changed (in a good way I believe). Feel free to submit a PR targeting that branch, otherwise I will inspire myself from your work 🙌

**Comment by martpie** [comment]
-> HMR works, but still needs to be optimzed
