### ISSUE TITLE
v5

### ISSUE THREAD

**Issue by martpie** [martpie/next-transpile-modules#115]
This is an issue to keep track of all the things for the next major version on `next-transpile-modules`. 

The popularity of this plugin is rising every month (> 180k weekly downloads at the time of this issue), and the use-cases and different setups used with this plugin are getting bigger and more complex.

Ok, let's go:

- [ ] Support all major package managers
  - [x] `npm` (via `file:`)
  - [x] `npm` (via workspaces)
  - [x] `yarn` (via workspaces)
  - [x] `yarn` 2 (berry)  #75 
    - [x] make it work
    - [x] `next-transpile-modules` is not working when called from `node_modules`
  - [x] (?) `pnpm`
- [ ] Add tests for hot-reloading
- [x] Debug mode #120 
- [x] Improve transpilation overrides
  - [x] (?) Switch to resolver rather than path matchers
  - [x] (?) Match package names rather than package paths #90 
- [ ] ~Webpack 5-only support (to-be-discussed)~
- [ ] (?) Serverless support #11 

(?) -> not sure, to be discussed

## Edit Nov 23rd: so you want to test it?

The branch is called `nextjs-10` (yes it is misleading). It is unstable and can break anytime. No API changes, but the internal behavior is completely different (we don't rely on regexes anymore, but on real package names). Make sure you have a valid `main` field in your `package.json` (you can put an empty `index.js` at the root if you want.

**Comment by belgattitude** [comment]
@martpie out of my mind: 

### NPM

NPM v7 will include workspaces support (like yarn: https://blog.npmjs.org/post/186983646370/npm-cli-roadmap-summer-2019). 

### Serverless support

For my use case, in production my repos always use published packages (lerna), I use next-transpile-modules only for convenience on sandboxes and development.

### Sharing config

There's missing recipes for tests (ts-jest, jest...). how would we share the config ?

*I've put some notes here: https://github.com/belgattitude/vercel-monorepo-test#proscons based on tsconfig paths improvements rather than next-transpile-modules... *

**Comment by martpie** [comment]
> There's missing recipes for tests (ts-jest, jest...). how would we share the config ?

Can you clarify what you mean?

> NPM v7 will include workspaces support

finallyyyy 😄

**Comment by ScriptedAlchemy** [comment]
Webpack 5 was released this morning. Your plugin works but I think it still has hmr issues last I checked. Been using a fork since issue raised. If not already addressed, can we look at fixing the regex patterns?

**Comment by martpie** [comment]
Hello there! Yep I saw that yesterday. I started migrating side projects to understand better the underlying changes.

Next.js 9.6 should be our fairly soon so I will have a look at that soon :)

**Comment by ScriptedAlchemy** [comment]
Excellent. My fork and I think your package has one issue I discovered yesterday when upgrading a big codebase. I'll patch the fork and open a PR. 

Lmk if you need anything

**Comment by ScriptedAlchemy** [comment]
Seems that my latest PR works at my company. Have released it to NPM

 
`@module-federation/next-transpile-modules@5.0.0-beta.6`

**Comment by belgattitude** [comment]
@ScriptedAlchemy @martpie Came late to the party, but I'm now testing the V5 and could not make it it work

Tried to upgrade an existing example project in https://github.com/belgattitude/vercel-monorepo-test/pulls with both `beta.5` and `@module-federation/next-transpile-modules@5.0.0-beta.6` (yarn workspace project)

Is there anything that have changed in the usage ? 

The one I used is https://github.com/belgattitude/vercel-monorepo-test/blob/f19fdc582677f074c7c531c949a711ea26f53f7d/apps/web-app/next.config.js#L6, unchanged from v4

```js
const withTM = require('next-transpile-modules')([
    '@optional-package-scope/foo',
])
```

**Comment by martpie** [comment]
@belgattitude Can you post the error? If it's a "cannot resolve blabla", make sure you have a valid `main` field in your `package.json`, this is one breaking change with the new version.

I'll need to document it at some point.

**Comment by belgattitude** [comment]
Yes I see now. Thanks I'm not fan of using this field though. 

It will be used to point to distributed file when you publish the package

```json
{
  "name": "@optional-package-scope/bar",
  "version": "1.0.0",
  "main": "dist/bar.js",
  "module": "dist/bar.module.js",
  //..
```

And then we'll be blocked somehow.

I know that some people might use things like a `source` param:

```json
{
  "name": "@optional-package-scope/bar",
  // differentiate source vs build
  "source": "src/index.ts",
  "main": "dist/bar.js",
```

But ultimately I'm wondering, if the config would benefit for explicit path declaration, i.e:

```js
const withTM = require('next-transpile-modules')([
   // Tuple with package name / path  
   ['@optional-package-scope/foo', '../..relative/package/path'],
   // Or a more conventional object:
   {
      name: '@optional-package-scope/foo',
      path: '../..relative/package/path'
    }
])
```

What are your thoughts ?

**Comment by martpie** [comment]
> Thanks I'm not fan of using this field though.

yeah, but that's kinda the standard 😄. You can also point it to a direct TS file if you're importing TypeScript. On one of my projects I have:

```
"main": "src/index.ts"
```

The main reason why it is necessary is because of the changes needed to support #75 and #90, which were really necessary. Now your package resolution is done via `require.resolve`, and not regexes, which were really error prone and hard to debug.

You know, it's like using `npm ci` instead of `npm install`, it's annoying at the beginning, but it's just the better way 😄

> But ultimately I'm wondering, if the config would benefit for explicit path declaration

I think it is more annoying than the `main` field, but that's subjective.

**Comment by belgattitude** [comment]
Thanks @martpie, I know there's no real standard here, but using `main` makes it almost impossible to publlish the package...

Why not using `source` as microbundle uses, and let the `main` clean ?

**Comment by martpie** [comment]
We're now using `enhanced-resove` to do this job, I don't know if it supports `source`, but it's probably not something we'll implement ourselves.

**Comment by ScriptedAlchemy** [comment]
Yeah I think we do something to a lesser extent when attempting to resolve Cache management
