### ISSUE TITLE
SCSS modules class hash different in `head` and `body`

### ISSUE THREAD

**Issue by danoc** [martpie/next-transpile-modules#117]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ

**Are you trying to transpile a local package or an npm package?**
@thumbtack/thumbprint-react

**Describe the bug**
When using an NPM package that uses SCSS modules, the classnames used in the HTML's `body` do not match those in the `head`.

This codebase demonstrates it:
https://codesandbox.io/s/scss-module-incorrect-hash-with-next-transpile-modules-n6wkw?file=/pages/index.js

**To Reproduce**

1. Visit https://codesandbox.io/s/scss-module-incorrect-hash-with-next-transpile-modules-n6wkw?file=/pages/index.js
2. Notice that the Pill component doesn't have styles.
3. Inspect the generated HTML for the Pill component. Notice that the SCSS module classes are there.
4. Notice that the `head` tag contains a `style` tag that contains the Pill component CSS but with different hashes at the end of the classnames.

**Expected behavior**

The classnames would match in the `body` and `head`.

**Setup**

- Next.js version: 9.5.3
- `next-transpile-modules` version: 4.1.0
- Node.js version: Unknown (CodeSandbox)
- `npm`/`yarn` version: Unknown (CodeSandbox)
- Operating System: Unknown (CodeSandbox)
- Webpack 4 or 5: 4

**Additional context**

I think this Next.js issue is for built-in support of what I'm trying to do:
https://github.com/vercel/next.js/issues/13282

**Comment by danoc** [comment]
I'm happy to help debug this or provide more information if needed.

**Comment by danoc** [comment]
I've narrowed down the issue. Next.js's `getCssModuleLocalIdent` function uses the file path to generate the hash for the classname.

https://github.com/vercel/next.js/blob/f0809316eec7eea09781a71cf514c0bacee4d7d2/packages/next/build/webpack/config/blocks/css/loaders/getCssModuleLocalIdent.ts#L23-L29

The `relativePath` for the classname in the `body` HTML is `node_modules/@thumbtack/thumbprint-react/dist/cjs/components/Pill/index.module.scss` but the `relativePath` for the classname in the `head` CSS is `node_modules/@thumbtack/thumbprint-react/dist/es/components/Pill/index.module.scss`. Notice that the `head` uses the ES module version whereas the `body` uses the Common JS version.

Is this related to the inner workings of `next-transpile-modules`? I don't understand why the `relativePath` would be different.

**Comment by danoc** [comment]
One workaround is to explicitly import the ES module version in the `import`:

```js
import { Pill } from "@thumbtack/thumbprint-react/dist/es/index";
// instead of import { Pill } from "@thumbtack/thumbprint-react";
```

But I'd love to understand why this happens.

**Comment by martpie** [comment]
Hello there! Thank you for the report, I have a lot on my plate right now, but I will try to have a look at this issue next week :)

**Comment by martpie** [comment]
@danoc is it still happening with the latest version of Next.js and the plugin?

**Comment by danoc** [comment]
@martpie — I didn't get a chance to try this out again, but I can probably do it this week.

**Comment by danoc** [comment]
Hi @martpie, looks like it is still an issue:

https://codesandbox.io/s/scss-module-incorrect-hash-with-next-transpile-modules-n6wkw

I've upgraded all of the dependencies to their latest versions.

**Comment by connor-baer** [comment]
I've stumbled upon the same issue using plain CSS modules (no SCSS). The issue appears both in development and production. I am using `next@11.1.2` and `next-transpile-modules@8.0.0`. 

@danoc, how did you figure out that the `head` uses the `es` version?

**Comment by connor-baer** [comment]
I was able to work around the issue by stripping the `/es/` and `/cjs` parts from the relative path in [`getCssModuleLocalIdent`](https://github.com/vercel/next.js/blob/f0809316eec7eea09781a71cf514c0bacee4d7d2/packages/next/build/webpack/config/blocks/css/loaders/getCssModuleLocalIdent.ts#L13-L15). This can be done by overriding the `getLocalIdent` function in the `next.config.js` file: 

```js
const loaderUtils = require('next/dist/compiled/loader-utils');
const path = require('path');
const { webpack } = require('next/dist/compiled/webpack/webpack');

const withTM = require('next-transpile-modules')(['@madebyconnor/bamboo-ui']);

/**
 * Adapted from https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack/config/blocks/css/loaders/getCssModuleLocalIdent.ts
 */
const regexLikeIndexModule = /(?<!pages[\\/])index\.module\.(scss|sass|css)$/;

function getCssModuleLocalIdent(context, _, exportName, options) {
  const relativePath = path
    .relative(context.rootContext, context.resourcePath)
    .replace(/\\+/g, '/')
    // HACK: This is the change that ensures that classnames match between server and client.
    .replace('/es/', '/')
    .replace('/cjs/', '/');

  // Generate a more meaningful name (parent folder) when the user names the
  // file `index.module.css`.
  const fileNameOrFolder = regexLikeIndexModule.test(relativePath)
    ? '[folder]'
    : '[name]';

  // Generate a hash to make the class name unique.
  const hash = loaderUtils.getHashDigest(
    Buffer.from(`filePath:${relativePath}#className:${exportName}`),
    'md5',
    'base64',
    5,
  );

  // Have webpack interpolate the `[folder]` or `[name]` to its real value.
  return (
    loaderUtils
      .interpolateName(
        context,
        fileNameOrFolder + '_' + exportName + '__' + hash,
        options,
      )
      .replace(
        // Webpack name interpolation returns `about.module_root__2oFM9` for
        // `.root {}` inside a file named `about.module.css`. Let's simplify
        // this.
        /\.module_/,
        '_',
      )
      // Replace invalid symbols with underscores instead of escaping
      // https://mathiasbynens.be/notes/css-escapes#identifiers-strings
      .replace(/[^a-zA-Z0-9-_]/g, '_')
      // "they cannot start with a digit, two hyphens, or a hyphen followed by a digit [sic]"
      // https://www.w3.org/TR/CSS21/syndata.html#characters
      .replace(/^(\d|--|-\d)/, '__$1')
  );
}

const nextConfig = {
  webpack(config) {
	// Modify the css loader config
    config.module.rules[3].oneOf.forEach((moduleLoader, i) => {
      Array.isArray(moduleLoader.use) &&
        moduleLoader.use.forEach((l) => {
          if (
            l.loader.includes('css-loader') &&
            !l.loader.includes('postcss-loader')
          ) {
            l.options = {
              ...l.options,
              modules: {
                ...l.options.modules,
                getLocalIdent: getCssModuleLocalIdent,
              },
            };
          }
        });
    });

    return config;
  },
};

module.exports = withTM(nextConfig);
```

**Comment by danoc** [comment]
@connor-baer, I don't remember how I figured out the `head` uses the `es` version. But here's another workaround that involves changing the Webpack config:

```js
config.resolve.alias['<package-name>'] = '<package-name>/path/to/dist/es/index.js';
```

**Comment by martpie** [comment]
@danoc thank you very much for sharing, maybe I should add that as a default in the plugin 🤔

**Comment by martpie** [comment]
That said, this issue means that the imported CSS files are in different multiple locations, so I'd verify your workspace setup too, and make sure all your packages are using the same version of the same package. Maybe use Yarn's `resolutions` field to ensure that too.
