### ISSUE TITLE
TypeError: modules.map is not a function

### ISSUE THREAD

**Issue by elchung** [martpie/next-transpile-modules#118]
- [X] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ

**Are you trying to transpile a local package or an npm package?**
Trying to transpile lodash-es

**Describe the bug**
I am getting `SyntaxError: Unexpected token 'export'. export { default as add } from './add.js'` when trying to run in a next.js project. Using next `v9.5.4-canary.14` and next-transpile-modules `v4.1.0`. 

**To Reproduce**
My `next.config.js` file is just 
```
const withTM = require('next-transpile-modules')(['lodash-es']);

module.exports = withTM({});

```

**Setup**

- Next.js version: `9.5.4-canary.14`
- `next-transpile-modules` version: `4.1.0`
- Node.js version: `12.16.1`
- `npm`/`yarn` version: `6.13.4`
- Operating System: `Windows 10`
- Webpack 4 or 5: `4.44.1`

**Additional context**
I unfortunately can't use a different lodash version since it's being used in the `Simplebar-react` project which I am using. Please let me know if there is any other information I can give.

**Comment by elchung** [comment]
didn't search closed issues. found similar issues reported

**Comment by elchung** [comment]
closed and reopened since I found a closed issue that reported the same bug I had (`modules.map is not a function`) and the comments there fixed that issue, but I got a different issue now. I edited my original question with the new error. It seems to me that next-transpile-modules isn't transpiling lodash-es, but i'm not sure if this is just a webpack issue...

**Comment by agentlewis** [comment]
@elchung Could you reference the other issue please so those of us finding this thread can see what you worked out - thanks

**Comment by elchung** [comment]
#67 Yup, sorry about that. I fixed the original modules.map is not a function issue based on comments from this issue.

**Comment by martpie** [comment]
Does it work with the latest stable of Next.js? Do you have a longer log? Do you have reproduction steps? It seems you are trying to transpile some ESM code from `node_modules` and it does not go through this plugin.
