### ISSUE TITLE
Global CSS cannot be imported from files other than your Custom <App>

### ISSUE THREAD

**Issue by jsakas** [martpie/next-transpile-modules#119]
Hi, I am trying to use NextJS with Microsoft's Monaco Editor and the accompanying `react-monaco-editor` package.

Monaco editor imports its own `.css` files into the "esm" build. Ref: https://github.com/microsoft/monaco-editor/issues/886

Hoping to get all these packages to play nice. The global css imports  issue is well known with Next, but I was hopeful this module would be able to handle it. 

- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ

**Are you trying to transpile a local package or an npm package?**

- `react-monaco-editor`
- `monaco-editor`

**Describe the bug**

```
wait  - compiling...
error - ./node_modules/monaco-editor/esm/vs/base/browser/ui/actionbar/actionbar.css
Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://err.sh/next.js/css-global
Location: node_modules/monaco-editor/esm/vs/base/browser/ui/actionbar/actionbar.js
```

**To Reproduce**

Run this repository and view the index: https://github.com/jsakas/nextjs-monaco

**Expected behavior**

It can transpile css files that are not `modules`.

**Setup**

https://github.com/jsakas/nextjs-monaco

```
yarn install
yarn dev
```

**Comment by Dammic** [comment]
In our own project, we've used:
```
const withTM = require('next-transpile-modules')([
  'monaco-editor',
]);
const withPlugins = require('next-compose-plugins');

module.exports = withPlugins(
  [
    [
      withTM,
      {
        webpack: config => {
          const rule = config.module.rules
            .find(r => r.oneOf)
            .oneOf.find(
              r =>
                // Find the global CSS loader
                r.issuer && r.issuer.include && r.issuer.include.includes('_app')
            );
          if (rule) {
            rule.issuer.include = [
              rule.issuer.include,
              // Allow `monaco-editor` to import global CSS:
              /[\\/]node_modules[\\/]monaco-editor[\\/]/,
            ];
          }
          return config;
        },
      },
    ],
  ],

```

That worked fine in 9.4.4, but unfortunately doesn't work right now in 9.5. I'm currently investigating if I can make it somehow work again in my case.

**Comment by martpie** [comment]
Hello there,

thank you for the request. I understand the frustration that Next.js imposes with this kind of rules, however I think it goes beyond the scope of this plug-in, so I don't think I will implement this.

My best recommendation for you is to hack your way around like @Dammic did. You can use `util.inspect` to understand how the Webpack config looks like, and then override some rules.

I think another really important aspect of it is understand **why** the Next.js team decided to add these rules (performances? best practices?). Plot twist: I have no idea. Then you can make up your own mind and decide if you really want that.

On a more personal note: I really encourage you to stay as close to Next.js core/defaults as possible. In the other way lies madness (I hate to say "trust me", but, trust me).

cheers!

**Comment by Dammic** [comment]
I can add from myself that I've ended up using https://github.com/suren-atoyan/monaco-react , which doesn't require all this hacking and works out of the box for me.

**Comment by jsakas** [comment]
@Dammic I appreciate the suggestion! I ultimately decided to move away from NextJS out of frustration that it cannot even handle the basic functionality of Webpack (in which it is built on) without a ton of headache and ultimately what I would consider to be a hack.

**Comment by martpie** [comment]
Out of curiosity, what was your final choice?

**Comment by jsakas** [comment]
@martpie in this case it was a static site, so I went with my own Webpack config and used Netlify's prerender function to get everything in the DOM on the initial load for SEO.
