### ISSUE TITLE
conflict with next-compose-plugins

### ISSUE THREAD

**Issue by gavinsharp** [martpie/next-transpile-modules#12]
Thanks for this plugin - solves a real problem for us!

I use `next-compose-plugins` in my `next.config.js`. My config before I started using this plugin looked like this:
```
const withPlugins = require('next-compose-plugins');

const withCSS = require('@zeit/next-css');
const withSass = require('@zeit/next-sass');
const withImages = require('next-images');

module.exports = withPlugins([
  withCSS,
  withSass,
  withImages,
], {
    webpack: (config, { dev }) => {
      const eslintRule = {
        // omitted for brevity
      };

      config.module.rules.unshift(eslintRule);

      return config;
    },
});
```

Then I added this plugin, ending up with something like:
```
module.exports = withPlugins([
  withTM({
    transpileModules: ['somemodule'],
  }),
  withCSS,
  withSass,
  withImages,
], {
  webpack: (config, { dev }) => {
     // custom webpack stuff
  },
});
```

The config passed to `withPlugins` broke when I added `withTM`. It seems to be silently ignored.

Through a painful process of driving myself crazy debugging, I realized that I needed to instead do something like:
```
module.exports = withPlugins([
  withTM({
    transpileModules: ['somemodule'],
    webpack: (config, { dev }) => {
       // custom webpack stuff
    },
  }),
  withCSS,
  withSass,
  withImages,
]);
```

I don't quite fully understand why this happened and haven't dug into it, but thought I would raise the issue here, so that it can either be fixed, or maybe just noted in the README.

**Comment by martpie** [comment]
From the doc: 

> note: please declare withTM as your last plugin (the "most nested" one).

With `withPlugins`, are plugins applied left-to-right or right-to-left?

**Comment by gavinsharp** [comment]
I did notice that, and tried to put withTM at the other end of the array, but that seemed to break loading of the other plugins entirely (errors loading CSS), so I assumed it was the “wrong way”. I didn’t get a chance to dig too much deeper into that.

**Comment by martpie** [comment]
Can you provide a repo with a reproduction of this problem? It will help me investigate where the problems are in the webpack configuration.

**Comment by gavinsharp** [comment]
> Can you provide a repo with a reproduction of this problem? It will help me investigate where the problems are in the webpack configuration.

Sure, here you go: https://github.com/gavinsharp/nptm-bug

I tried to simplify it and remove unnecessary dependencies.

**Comment by martpie** [comment]
@gavinsharp Thank you for the repro. I do not manage to get the same error than you, (I commented the `webpack` line).

Can you?

If yes, what is your operating system and node/npm versions?

**Comment by martpie** [comment]
Well, this is interesting:

```
const withPlugins = require('next-compose-plugins');

const withSass = require('@zeit/next-sass');
const withTM = require('next-plugin-transpile-modules');

module.exports = withPlugins([
  withTM({
    transpileModules: ['empty'],
  }),
  withSass,
], {
  webpack: (config, { dev }) => {
    throw "custom webpack config";
  },
});
```

does nothing (it works), but

```
const withPlugins = require('next-compose-plugins');

const withSass = require('@zeit/next-sass');
const withTM = require('next-plugin-transpile-modules');

module.exports = withPlugins([
  withTM,
  withSass,
], {
  transpileModules: ['empty'],
  webpack: (config, { dev }) => {
    throw "custom webpack config";
  },
});
```

throws.

**Comment by martpie** [comment]
Ok, I tried a more complete solution like yours: 

```
const withTypescript = require('@zeit/next-typescript');
const withPlugins = require('next-compose-plugins');
const withTM = require('next-plugin-transpile-modules');

const withCSS = require('@zeit/next-css');
const withSass = require('@zeit/next-sass');
const withImages = require('next-images');

module.exports = withPlugins([
  withTM({
    transpileModules: ['shared'],
  }),
  withTypescript,
  withCSS,
  withSass,
  withImages,
], {
  webpack(config, options) {
    if (options.isServer && options.dev) {
      const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

      config.plugins.push(
        new ForkTsCheckerWebpackPlugin({
          tsconfig: '../tsconfig.json',
          tslint: '../tslint.json',
        }),
      );
    }

    return config;
  },
});
```

I am running it with no problems: my `shared` package written in TypeScript is being transpiled correctly.

**Comment by gavinsharp** [comment]
> @gavinsharp Thank you for the repro. I do not manage to get the same error than you.
> 
> Can you?
> 
> If yes, what is your operating system and node/npm versions?

Which step were you trying? I tried to list all the steps and log output explicitly in the repo README:
https://github.com/gavinsharp/nptm-bug/blob/master/README.md

I am using node 8.12/npm 6.7.0 on Mac OS 10.14.

**Comment by martpie** [comment]
I misunderstood your problem, I understand better now 😄

I'll investigate more tonight!

**Comment by martpie** [comment]
I can reproduce the bug with other plugins like `with-typescript`, it may not be related to this plugin but to Next.js or `next-compose-plugins` directly.

Still investigating.

**Comment by martpie** [comment]
@gavinsharp You are using the `next-compose-plugins` wrong: your `next.config.js` should look like:

```
const withPlugins = require('next-compose-plugins');

const withSass = require('@zeit/next-sass');
const withTM = require('next-plugin-transpile-modules');

module.exports = withPlugins([
  [withTM, {
    transpileModules: ['empty'],
  }],
  withSass,
], {
  webpack: (config, { dev }) => {
    throw "custom webpack config";
    return config;
  },
});
```

From the docs: https://github.com/cyrilwanner/next-compose-plugins#extend-another-config-file

Please tell me if it fixed it for you ;)

**Comment by gavinsharp** [comment]
Sorry for the delayed response - I appreciate you spending time investigating this! I admit I'm still not really following why my first attempt didn't work, but that's probably a misuse/misunderstanding of `next-compose-plugins`, as you mention.
