### ISSUE TITLE
Problem working with experimental decorators.

### ISSUE THREAD

**Issue by jamieowen** [martpie/next-transpile-modules#128]
- [X] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [X] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ

**Are you trying to transpile a local package or an npm package?**
If an npm package, which one?
A local one. in a yarn workspaces style setup.

**Describe the bug**
I'm having a problem getting decorators working with modules. 
This is probably a simple fix but I'm stuck for ideas.

I have defined a babel.config.js like in the next project:
``` javascript 
module.exports = {
  presets: [["next/babel", { "class-properties": { loose: true } }]],
  plugins: [["@babel/plugin-proposal-decorators", { legacy: true }]],
};
```

The decorators work in a 'non module' and my modules are being picked up correctly when not using decorators. Except plugins are not being processed. I assumed plugins ( defined in babel.config.js ) would be picked up automatically or do i need to add to the next.config.js?

Or do I also need to define babel.rc relative to packages? ( but my understanding was that babel.config.js should be project wide )

Any help would be appreciated!

**To Reproduce**
... 

**Expected behavior**
Experimental decorators are transpiled correctly

**Setup**

- Next.js version:9.5.5
- `next-transpile-modules` version:4.1.0
- Node.js version: 14.13.1
- `npm`/`yarn` version: 6.14.8 / 1.22.10
- Operating System: OSX
- Webpack 4

**Additional context**
...

**Comment by martpie** [comment]
Please use the default issue templates 👍

**Comment by jamieowen** [comment]
apologies!.. updated.. let me dig into this some more!

**Comment by jamieowen** [comment]
Hey @martpie, so probably ok to close this.
Was related to #101, using absolute paths with scoped packages.

Not the most fun to debug.  I did have this fix in but changed it - as the decorators were not actually the problem, another webpack warning seemed to be causing the babel transform to fail. 

Fun times...

Thanks for maintaining this plugin anyway.
Has Next.js/Vercel ever mentioned supporting transpiling modules properly?

**Comment by martpie** [comment]
Ah I see, maybe I should add a note about scoped packages in the README 👍

Regarding the "native" support of transpiling modules, I have no news from the Next.js team. I know that they know this plugin is extremely popular (35% of Next.js users uses it), and they sometimes open issues to tell me of potential new features/changes 😄

I think they are happy to not have to maintain it, but I also believe it's definitely on their roadmap, but just not of a really high priority right now.
