### ISSUE TITLE
Trouble migrating 2.3.1 -> 4.1.0 in Next 9.5.3 project

### ISSUE THREAD

**Issue by gtodd876** [martpie/next-transpile-modules#129]
I've been debugging through v.4 of next-transpile-modules as compared to v.2.3.1 and I've found out that if I use the `includes` regex from version 2.3.1 in version 4.1.0 then it will transpile my js with babel otherwise it will not with the newer version 4 regex.
Here's how the regex looks different between the two versions:
```js
const transpileModulesVersion4 = {
  includes: [
    /(@kmx[\\/]legos-react|@kmx[\\/]legos|@material)$/,
    /(@kmx[\\/]legos-react|@kmx[\\/]legos|@material)[\\/](?!.*node_modules)/,
  ],
  excludes: [
    /node_modules[\\/](?!(@kmx[\\/]legos-react|@kmx[\\/]legos|@material)([\\/]|$)(?!.*node_modules))/,
  ],
};

const transpileModulesVersion2 = {
  includes: [
    /@kmx[\\/]legos-react(?!.*node_modules)/,
    /@kmx[\\/]legos(?!.*node_modules)/,
    /@material(?!.*node_modules)/,
  ],
  excludes: [
    /node_modules[\\/](?!(@kmx[\\/]legos-react|@kmx[\\/]legos|@material)(?!.*node_modules))/,
  ],
};
```
... If I use v.4 without modifying the package with the `includes` regex from version 2.3.1 then my modules are left as is and IE11 crashes on the first arrow function syntax it sees. Is this a bug I've found or maybe I'm missing an option I need to declare in the migration process?

next.config.js - for v.4
```js
const withTranspileModules = require('next-transpile-modules')(['@kmx/legos-react', '@kmx/legos', '@material']);
```

**Comment by martpie** [comment]
Please use the default issue template.
