### ISSUE TITLE
What's the workflow for published (compiled / built) modules?

### ISSUE THREAD

**Issue by borekb** [martpie/next-transpile-modules#133]
We've been happy users of next-transpile-modules for a long time but it has always been in private monorepos only, with Yarn workspaces. Now we're going to publish some of our packages (libraries) to npm and I'm wondering if that isn't at odds with this module.

For example, our `lib` currently doesn't specify a `main` field in its `package.json` and we just consumed its `index.ts` (TypeScript file) like this in a Next.js app:

```ts
import SomeComponent from '@company/lib';
```

Now this `lib` is going to be published to npm, meaning there will be a build process producing `dist/index.js` and the `package.json` will have `"main": "dist/index.js"` in it. What does this mean for next-transpile-modules? Should we still configure it to transpile our library?

I'm sure people do this but I can't quite figure out how to use next-transpile-modules "locally" while also having a build process and an updated package.json for eventual publishing to npm.

**Comment by martpie** [comment]
If you are importing common JS/a build library, you don't need this library.
If you are importing ES modules/TypeScript/anything not transpiled, you need this library.

Publishing is not part of the scope of this plugin, you will have to define your `main` fields, packaging etc by yourself.

**Comment by martpie** [comment]
FYI, I'm having a similar setup on one project, what I ended up doing is:

`import { Button } from 'styleguide'` and `import { Button } from 'styleguide/cjs'` to disctinct the two. The first one is using `next-transpile-modules`, the other one is not.

**Comment by borekb** [comment]
Right, so two imports. I was wondering whether it's somehow possible to have a single import and use next-transpile-modules during development and built/compiled modules during production deployment, but that's not possible. Hmm, this will be a tough decision.

**Comment by martpie** [comment]
I did not investigate two much this way, but tweaking the `resolve` configuration may work. Something like "if you require `styleguide`", require `styleguide/cjs` instead. I am not sure if it's really better.

**Comment by borekb** [comment]
Interesting, any example of how / where this would be done? I've never really messed with `resolve` and think it's a dangerous thing because e.g. Yarn PnP patches it as well but maybe it's one of the few options we have.

Like, for local development, we really don't want to lose the elegance of next-transpile-modules, so much so we're even considering publishing raw TypeScript to npm and force users to set up next-transpile-modules 😄. But that puts the user at risk because for example if they want to use Yarn PnP, next-transpile-modules will not work for them (#75).

So I'm trying to work out what's the best compromise is.
