### ISSUE TITLE
CSS imports in node_module deps triggers NextJS CSS global error

### ISSUE THREAD

**Issue by SpyTec** [martpie/next-transpile-modules#134]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ

**Are you trying to transpile a local package or an npm package?**
npm package: `@patternfly/react-core`

**Describe the bug**
`next.config.js`
```js
const withTM = require("next-transpile-modules")(['@patternfly/react-core', '@patternfly/react-table', '@patternfly/react-styles', '@patternfly']);

module.exports = withTM();
```

```js
> next build

Loaded env from /home/spytec/Documents/JavaScriptProjects/project/.env
info  - Creating an optimized production build  
Failed to compile.

./node_modules/@patternfly/react-styles/css/components/AboutModalBox/about-modal-box.css
Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.tsx. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://err.sh/next.js/css-global
Location: node_modules/@patternfly/react-styles/css/components/AboutModalBox/about-modal-box.js
```

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):
Dependencies: `@patternfly/react-core next next-transpile-modules `

https://codesandbox.io/s/heuristic-silence-dmu5y?file=/pages/index.js

**Expected behavior**
JS dependency importing CSS is handled

**Setup**

- Next.js version: v9.5.5, v10.0.0
- `next-transpile-modules` version: v4.1.0
- Node.js version: v10.19.0
- `npm`/`yarn` version: v6.13.4
- Operating System: Fedora 32
- Webpack 4 or 5: 4

**Additional context**
I'm unsure whether this library intends to handle CSS imports in `node_modules`, but so far I've not found any better solutions that isn't replacing the whole NextJS webpack config

**Comment by martpie** [comment]
Can you try with `const withTM = require("next-transpile-modules")(['@patternfly']);` only and tell me if it works?

**Comment by SpyTec** [comment]
Just tried it, gives the same global CSS error

**Comment by martpie** [comment]
I have tests that are supposed to handle this case: https://github.com/martpie/next-transpile-modules/tree/master/src/__tests__/__apps__/_shared-ui/components 

do you see any difference between that and your setup?

**Comment by SpyTec** [comment]
I see two differences, PatternFly doesn't import CSS as modules - instead it's plain CSS imports

Second thing is that it's not a package in node_modules, which the issue I encounter happens in. For example when I `import { Button } from '@patternfly/react-core'` in my code, the CSS import that happens will be in the Button component in the PatternFly dependency in node_module

**Comment by martpie** [comment]
Ah, I see I got it.

I don't think it's possible to do it the way you want. `next-transpile-modules` really apply the same rules as the default Next.js config. So imported CSS from your components will be considered CSS modules.

That said, in Next.js 10, there is this: https://nextjs.org/blog/next-10#importing-css-from-third-party-react-components, which should solve your usecase, no?

**Comment by martpie** [comment]
For your usecase, I think you should just aggregate all CSS files in one (via imports for example), and just import the whole aggregation once in _app

**Comment by SpyTec** [comment]
I see, thanks.

That feature in Next 10 is only for importing CSS from third-party dependencies, won't work in my case as those dependencies are the ones importing the CSS. I was trying to expand the Next webpack rules to use `null-loader` with PatternFly's CSS imports but had no luck

**Comment by martpie** [comment]
If you find a solution to your problem, I'd be interested to know how you fixed it! :) good luck!
