### ISSUE TITLE
New resolution strategy causes problems in single-repo approach

### ISSUE THREAD

**Issue by goloroden** [martpie/next-transpile-modules#137]
Hey 👋 

We're using Next.js 10.0.3 together with next-transpile-modules. So far, everything worked smoothly, but now we've run into a major issue with the new resolution strategy introduced in next-transpile-modules v5.

The problem is a follows: We have a single repository, which contains multiple Next.js applications, and a shared folder with components that are used by all these applications. Basically the repository layout is like this:

```
/
  applications/
    nextApp1/
      pages/
        ...
      next.config.js
      tsconfig.json
    nextApp2/
      pages/
        ...
      next.config.js
      tsconfig.json
  components/
    Foo.tsx
    Bar.tsx
  package.json
  tsconfig.json

```

As you can see, we are only using a single `package.json` file at the root level, and we are using TypeScript. So, to keep things simple we have been using next-transpile-modules in both Next.js applications to include the `/components/` folder, so that we can use the components without first having to compile them manually, which would be a major disadvantage, especially for HMR in development mode.

OTOH we didn't want to turn this into a mono repo using Lerna, or something like that, since the simple structure here makes things easier to maintain, especially since all the Next.js applications shall actually be part of a *single* npm module in the end.

So far, this structure worked very well. With next-transpile-modules v5 things have broken: Next.js now complains about not being able to resolve the module `/components`, since there is no `package.json`and no `index.js` file. If we add them as dummy files, then Next.js complains about not being able to find React.

To cut a long story short: What we try to achieve is to transpile code from outside a Next.js application, which is not a standalone npm package, and which *shall not be* a standalone npm package.

Is this possible, and if so, do you have any hint on what we are doing wrong?

**Comment by martpie** [comment]
Hello there 👋

If you're not using a monorepo approach, that means your components are not in `node_modules`? I don't even understand how it works with `next-transpile-modules` 4 tbh 😄

Can you show me a sample of your `package.json`?

**Comment by martpie** [comment]
Closing as this is a little bit out of scope of this project. I'll re-open if there's an answer and it makes sense to support this usage.

**Comment by vvo** [comment]
I was facing the same issue, I have been using Next.js's "Absolute Imports and Module path aliases" (https://nextjs.org/docs/advanced-features/module-path-aliases) and had this structure:

```js
// next.config.js
const withTM = require("next-transpile-modules")([
  "components", // local folder
  "react-select-search", // node_modules/react-select-search
]);
``` 

Structure:
```txt
- components
  - Header.js
- pages
  - index.js
```

```js
// pages/index.js
import Header from "components/Header"; 
```

And I think at some point to achieve this ^ you had to use next-transpile-modules, but it's no more the case. Next.js will transpile things that are present in jsconfig.js nowadays, by default.

**Comment by martpie** [comment]
So is your problem solved? :)

**Comment by vvo** [comment]
Yes :) only use next transpile modules for node_modules, not local folders

**Comment by martpie** [comment]
perfect 👍

**Comment by amitava82** [comment]
I'm sorry, are you saying it is not possible to use this without monorepo? I have following structure, and I'm using TS.
```
/
  src
    app
    app2
```
I want to import components from app into app2. Is this doable with this plugin? If so, is there any example I can look at. Or using monorepo if that's doable.

**Comment by martpie** [comment]
Where are the `package.json` in your project? If at the root, you don't need this plugin.

**Comment by amitava82** [comment]
At the root. I tried without any plugin. Both folder with own .bablelrc and tsconfig.json but Typescript stated complaining even after adding the `app` folder in the`include` of `app2` tsconfig.

**Comment by martpie** [comment]
Please read the FAQ
