### ISSUE TITLE
v5 - enhanced-resolve has problems with exports section and dot  

### ISSUE THREAD

**Issue by allanmc** [martpie/next-transpile-modules#139]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**
react-hook-form@6.12.1

**Describe the bug**
`enhanced-resolve` fails when resolving the exports section of react-hook-forms package.json:

```
Error: Package path . is not exported from package C:\xxx\node_modules\react-hook-form (see exports field in C:\xxx\node_modules\react-hook-form\package.json)
    at C:\xxx\node_modules\next-transpile-modules\node_modules\enhanced-resolve\lib\ExportsFieldPlugin.js:104:7
```

The section reads:
```
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "import": "./dist/index.esm.js",
      "require": "./dist/index.js"
    },
    "./dist/index.ie11": {
      "import": "./dist/index.ie11.js",
      "require": "./dist/index.ie11.js"
    }
  },
```

**To Reproduce**
Just try to transpile react-hook-form@6.12.1.

**Expected behavior**

**Setup**

- Next.js version:
- `next-transpile-modules` version: 5.0.0
- Node.js version: 10.0.3
- `npm`/`yarn` version: yarn 1.22.10
- Operating System: Windows 10
- Webpack 4 or 5: Webpack 4.44.1

**Comment by martpie** [comment]
Hello there 👋

What's your usecase for wanting to transpile ‘react-hook-form`?

**Comment by allanmc** [comment]
> Hello there 👋
> 
> What's your usecase for wanting to transpile ‘react-hook-form`?

We had compatibility issues with IE11 and Edge. I can see they now have a precompiled ie11 version - we'll use that instead of next-transpile-modules now 😃  
But i guess the support for `exports` like used by react-hook-form would still be nice to have working, or?

**Comment by martpie** [comment]
> We had compatibility issues with IE11 and Edge. I can see they now have a precompiled ie11 version - we'll use that instead of next-transpile-modules now 😃

My point exactly 😄 I had to use react-hook-forn and this is why I ended up doing. The import is not satisfying but it's working fine.

I will investigate the use of `exports` (I've never faced them before), but having read a little bit about it, I would think that the problem comes from `react-hook-form`, as `exports` is a webpack feature, and `enhanced-resolve` is coming from Webpack as well.

I'll do some research 👍

**Comment by martpie** [comment]
I'll close this as your problem is solved :)

**Comment by ssylvia** [comment]
@martpie I also ran into this issue with `nanoid` package. 

```sh
/Users/{PATH}/node_modules/next-transpile-modules/src/next-transpile-modules.js:70
    throw new Error(`next-transpile-modules - an unexpected error happened when trying to resolve "${module}"\n${err}`);
    ^

Error: next-transpile-modules - an unexpected error happened when trying to resolve "nanoid"
Error: Package path . is not exported from package /Users/{PATH}/node_modules/nanoid (see exports field in /Users/{PATH}/node_modules/nanoid/package.json)
```

Were transpiling nanoid for IE compatibility: https://github.com/ai/nanoid#ie

**Comment by martpie** [comment]
I don't see any `exports` here https://github.com/ai/nanoid/blob/main/package.json 🤔

**Comment by ssylvia** [comment]
@martpie This is what the package.json file looks like in when it gets installed: https://cdn.jsdelivr.net/npm/nanoid/package.json

```json
{
  "name": "nanoid",
  "version": "3.1.20",
  "description": "A tiny (108 bytes), secure URL-friendly unique string ID generator",
  "keywords": [
    "uuid",
    "random",
    "id",
    "url"
  ],
  "engines": {
    "node": "^10 || ^12 || ^13.7 || ^14 || >=15.0.1"
  },
  "author": "Andrey Sitnik <andrey@sitnik.ru>",
  "license": "MIT",
  "repository": "ai/nanoid",
  "browser": {
    "./index.js": "./index.browser.js"
  },
  "react-native": "index.js",
  "bin": "./bin/nanoid.cjs",
  "sideEffects": false,
  "types": "./index.d.ts",
  "type": "module",
  "main": "index.cjs",
  "module": "index.js",
  "exports": {
    ".": {
      "browser": {
        "development": "./index.dev.js",
        "production": "./index.prod.js"
      },
      "require": "./index.cjs",
      "import": "./index.js",
      "types": "./index.d.ts"
    },
    "./package.json": "./package.json",
    "./async/package.json": "./async/package.json",
    "./async": {
      "browser": "./async/index.browser.js",
      "require": "./async/index.cjs",
      "import": "./async/index.js"
    },
    "./non-secure/package.json": "./non-secure/package.json",
    "./non-secure": {
      "require": "./non-secure/index.cjs",
      "import": "./non-secure/index.js"
    },
    "./url-alphabet/package.json": "./url-alphabet/package.json",
    "./url-alphabet": {
      "require": "./url-alphabet/index.cjs",
      "import": "./url-alphabet/index.js"
    },
    "./index.d.ts": "./index.d.ts"
  }
}
```

**Comment by martpie** [comment]
-> https://github.com/ai/nanoid/issues/234

**Comment by martpie** [comment]
I opened a separate issue, the problem might be on our side
