### ISSUE TITLE
New resolution strategy breaks with @formatjs/intl-numberformat

### ISSUE THREAD

**Issue by ValentinH** [martpie/next-transpile-modules#140]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ

**Are you trying to transpile a local package or an npm package?**
I'm transpiling `@formatjs/intl-numberformat` with the new version 5 of `next-transpile-modules`. With version 4, I don't have any issues.

**Describe the bug**
I get the following build error:
```
Error: Can't resolve '@formatjs/intl-numberformat' in '/Users/valentin/test'
    at finishWithoutResolve (/Users/valentin/test/node_modules/enhanced-resolve/lib/Resolver.js:293:18)
...
> Build error occurred
Error: next-transpile-modules: could not resolve module "@formatjs/intl-numberformat". Are you sure the name of the module you are trying to transpile is correct?
```

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):
- install `@formatjs/intl-numberformat`
- add it to the list of `withTM([])`

**Expected behavior**
The build should not failed and the module should be transpiled.

**Setup**

- Next.js version: 10.0.1
- `next-transpile-modules` version: 5.0.0
- Node.js version: 12.18.4
- `npm`/`yarn` version: 1.22.4
- Operating System: MacOS
- Webpack 4 or 5: 4

**Additional context**
I guess it's due to `@formatjs/intl-numberformat` "main" field being wrong: https://github.com/formatjs/formatjs/issues/2365

If yes, could we have a more explicit error message? Here it could have tell me that the package was found but the "main" field was not pointing to a valid file. What do you think?

**Comment by martpie** [comment]
Hello 👋

As you have pointed out, the issue comes from the package itself.

That said, there is a second issue related to #138, and this pushes for an implementation of what I've talked about here: https://github.com/martpie/next-transpile-modules/issues/138#issuecomment-735649343

I will think about it, it's quite high priority, I just have to check now if I'm going to make an option out of it, or the default. If the default, that would be a breaking change.

As a temporary workaround, you can point `withTM` to any module (not only a package), so you could do `withTM(['@formatjs/intl-numberformat/my-entry-point-or-whatever.js'])`

**Comment by martpie** [comment]
@ValentinH I have a beta version ready, would you be interested in testing it?

**Comment by ValentinH** [comment]
Yes sure I can try it :)

**Comment by martpie** [comment]
`yarn add next-transpile-modules@martpie/next-transpile-modules#resolve-modules-to-their-root-package-json` should do the trick ;)

**Comment by ValentinH** [comment]
I get the following error:
```
> Build error occurred
Error: next-transpile-modules - an unexpected error happened when trying to resolve "@formatjs/intl-numberformat"
Error: Can't resolve '@formatjs/intl-numberformat' in '/Users/valentin/test'
    at getModuleRootDirectory (/Users/valentin/test/node_modules/next-transpile-modules/src/next-transpile-modules.js:70:11)
    at Array.map (<anonymous>)
    at generateResolvedModules (/Users/valentin/test/node_modules/next-transpile-modules/src/next-transpile-modules.js:81:35)
    at withTM (/Users/valentin/test/node_modules/next-transpile-modules/src/next-transpile-modules.js:110:29)
    at /Users/valentin/test/node_modules/next-compose-plugins/lib/compose.js:100:23
    at Array.forEach (<anonymous>)
    at composePlugins (/Users/valentin/test/node_modules/next-compose-plugins/lib/compose.js:77:11)
    at /Users/valentin/test/node_modules/next-compose-plugins/lib/index.js:22:38
    at normalizeConfig (/Users/valentin/test/node_modules/next/dist/next-server/server/config.js:7:494)
    at loadConfig (/Users/valentin/test/node_modules/next/dist/next-server/server/config.js:8:131)
```

I guess this is because of the main field pointing to a missing file, right?

**Comment by martpie** [comment]
Yes most probably 😩

**Comment by ValentinH** [comment]
The issue in `@formatjs/intl-numberformat` has been fixed. However, I noticed another issue (but that's fixed by #141 😃).

With this list of dependencies:
```
withTM([
  'use-deep-compare',
  'internal-1',
  'internal-2',
  'react-intl',
  'normalize-url',
  'query-string',
  'split-on-first',
  'strict-uri-encode',
])
```

the build succeeds, but several packages are not transpiled. If I use the `resolve-modules-to-their-root-package-json` branch, it works fine.

**Comment by martpie** [comment]
great, thanks for confirming that 👍 I will release something today

**Comment by martpie** [comment]
-> `6.0.0`

**Comment by alexandregme** [comment]
I upgraded to the latest version and I am getting this error now `Error: next-transpile-modules: could not resolve module "styleguide". Are you sure the name of the module you are trying to transpile is correct?`

**Comment by martpie** [comment]
@alexandregme Please open a new issue with more context 👍
