### ISSUE TITLE
How to traspile my Nextjs webapp to work fine in IE11 (arrow functions don't work yet)

### ISSUE THREAD

**Issue by anialamo** [martpie/next-transpile-modules#150]
- [X ] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [ X] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ (you may not get support if you remove this line)

**Are you trying to transpile a local package or an npm package?**
I want to traspile my own code like components or pages useEffect hook.
Because I see in all my code that arrow functions are not executed. Like this:

![image](https://user-images.githubusercontent.com/35197781/102392529-777aff00-3fd7-11eb-8505-4ba058b9dec5.png)

 
I have this next.config.js
```
const withSass = require("@zeit/next-sass");

const withTM = require('next-transpile-modules')([]); // pass the modules you would like to see transpiled, I only need my own code

const localeLanguages = [
     { label: 'en', name: 'English' },
     { label: 'es', name: 'Español' }     
];

// Extend your Next config for advanced behavior
// See https://nextjs.org/docs/api-reference/next.config.js/introduction
let nextConfig = {
     
     publicRuntimeConfig: {
          localeLanguages
     },

     i18n: {
          // These are all the locales you want to support in
          // your application
          locales: ['en', 'es'],
          // This is the default locale you want to be used when visiting
          // a non-locale prefixed path e.g. `/hello`
          defaultLocale: 'en',
          localeDetection: true,
     },     
};
// Add the Next SASS plugin
nextConfig = withSass(withTM(nextConfig));

module.exports = nextConfig;

```
**Describe the bug**
Testing in Windows 10 IE11 any arrow function works.

My Nextjs code has the following file structure:

![image](https://user-images.githubusercontent.com/35197781/102394361-ece7cf00-3fd9-11eb-8792-139f4d34d2d7.png)

**Setup**

- Next.js version: 10.0.3
- `next-transpile-modules` version: 6.0.0  
- Operating System: Windows 10
- Webpack: 5 
 
**Github code**
My source is:
https://github.com/anialamo/nootric-next10

**Comment by martpie** [comment]
Please check the issue template checkboxes or you may not get support.

**Comment by anialamo** [comment]
Ok! Sorry I forget to check them! I will pay or colabore but I need support please @martpie 
Thanks!

**Comment by anialamo** [comment]
I need to open a new Issue? @martpie

**Comment by martpie** [comment]
No worries, it's really to make sure people understand the usual problems before I have to spend some time supporting them.

So I am not sure to understand your problem.

> I want to traspile my own code like components or pages useEffect hook.
> Because I see in all my code that arrow functions are not executed. Like this:

> Testing in Windows 10 IE11 any arrow function works.

I am getting mixed signals here.

Also looking at your setup/file structure, I think you are mis-using `next-transpile-modules`. This plugin is only used to transpile code coming from `node_modules` (let it be a local linked package, or a package from npm), not the code of your app itself. This is the responsibility of Next.js

If your arrow functions (in your app files) are not firing, I think you might by mis-using React. Can you maybe show a full file?

**Comment by martpie** [comment]
Waiting for a reply, I'll close this in the meantime.
