### ISSUE TITLE
next-transpile-modules - an unexpected error happened when trying to resolve

### ISSUE THREAD

**Issue by alexandregme** [martpie/next-transpile-modules#153]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
I am using a private styleguide, on gitlab. The issue happens when I am using yarn link to transpile it locally. 

**Describe the bug**

this import happens on the stylguide level.
`import Layout from '../layout';`

this is how I wanted to use it, `components` is on the root level.
`import Layout from 'components/app/layout';`

The error is thrown on the application level that cannot resolve the path.
`
Failed to compile
./node_modules/styleguide/components/app/companyapp/companyapp.js:3:0
Module not found: Can't resolve 'components/app/layout'
null
`

**To Reproduce**
npm link - at the styleguide project
npm link styleguide - at the application project
yarn dev 

**Expected behavior**
the modules transpile should know how to handle the paths to resolve the files.

**Setup**

- Next.js version: "^10.0.3",
- `next-transpile-modules` version: 4.1.0
- Node.js version:
- `npm`/`yarn` version:
`"engines": {
    "node": ">=14.15.0",
    "yarn": ">=1.22.4"
  },`
- Operating System: macOS Catalina
- Webpack 4 or 5: 4

If I upgrade it to 6.0.0 the error changes to 

```Error: next-transpile-modules - an unexpected error happened when trying to resolve "styleguide"
Error: Can't resolve 'styleguide' in '/Users/amendes/workpace/app/apppage'
    at getPackageRootDirectory (/Users/amendes/workpace/app/apppage/node_modules/next-transpile-modules/src/next-transpile-modules.js:70:11)
    at Array.map (<anonymous>)
    at generateModulesPaths (/Users/amendes/workpace/app/apppage/node_modules/next-transpile-modules/src/next-transpile-modules.js:81:33)
    at withTM (/Users/amendes/workpace/app/apppage/node_modules/next-transpile-modules/src/next-transpile-modules.js:110:26)
    at Object.<anonymous> (/Users/amendes/workpace/app/apppage/next.config.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

**next.config.js**

```const path = require('path');
const withSass = require('@zeit/next-sass');
const withTM = require('next-transpile-modules')(['styleguide'], {debug:true, resolveSymlinks:true});

module.exports = withTM(withSass(
  {
    webpack(config) {
      const c = config;
      c.resolve.alias.actions = path.join(__dirname, 'actions');
      c.resolve.alias.components = path.join(__dirname, 'components');
      c.resolve.alias.pages = path.join(__dirname, 'pages');
      c.resolve.alias.pagestyle = path.join(__dirname, 'pagestyle');
      c.resolve.alias.reducers = path.join(__dirname, 'reducers');
      c.resolve.alias.selectors = path.join(__dirname, 'selectors');
      c.resolve.alias.shared = path.join(__dirname, 'shared');
      c.resolve.alias.react = path.resolve('./node_modules/react');
      c.module.rules.push(
        {
          test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
          use: {
            loader: 'url-loader',
          },
        },
      );
      return c;
    },
    trailingSlash: true,
    async exportPathMap() {
      return {
        '/': { page: '/apppage' },
      };
    },
  },
));
```

**Comment by martpie** [comment]
Can you paste your Styleguide's `package.json` here + a screenshot of the file structure of the project?

**Comment by alexandregme** [comment]
`
{
  "name": "styleguide",
  "version": "0.0.35",
  "private": true,
  "engines": {
    "node": ">=14.15.0",
    "yarn": ">=1.22.4"
  },
  "scripts": {
    "test": "jest --coverage --no-cache --runInBand --forceExit",
    "test:watch": "yarn test --watchAll",
    "test:release": "jest --no-cache --runInBand --forceExit",
    "styleguide": "styleguidist server",
    "styleguide:build": "yarn test --silent && styleguidist build && cp -rf ./coverage/lcov-report ./styleguide/coverage",
    "eslint": "eslint ./ --color",
    "eslint:fix": "yarn eslint --fix",
    "release": "np",
    "on": "mv node_modules/reactt node_modules/react",
    "off": "mv node_modules/react node_modules/reactt",
    "fresh": "rm -rf ./coverage ./node_modules ./styleguide ./yarn-error.log package-lock.json && npm cache clear --force && yarn cache clean && yarn install"
  },
  "peerDependencies": {
    "babel-plugin-inline-react-svg": "^1.1.2",
    "classnames": "^2.2.6",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-jss": "^10.5.0",
    "bootstrap-scss": "^4.5.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.12.1",
    "@babel/core": "^7.12.3",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.5",
    "@testing-library/jest-dom": "^5.11.6",
    "@testing-library/react": "^11.1.1",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.1.0",
    "babel-plugin-inline-react-svg": "^1.1.2",
    "babel-plugin-module-resolver": "^4.0.0",
    "bootstrap-scss": "^4.5.3",
    "classnames": "^2.2.6",
    "css-loader": "^5.0.1",
    "deep-freeze": "^0.0.1",
    "eslint": "^7.13.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jest-dom": "^3.3.0",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-testing-library": "^3.10.1",
    "file-loader": "^6.2.0",
    "jest": "^26.6.3",
    "module-resolver": "^1.0.0",
    "node-sass": "^5.0.0",
    "np": "^7.0.0",
    "pre-commit": "^1.2.2",
    "pre-push": "^0.1.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-jss": "^10.5.0",
    "react-styleguidist": "^11.1.1",
    "sass-loader": "^10.1.0",
    "style-loader": "^2.0.0",
    "webpack": "4.44.2"
  },
  "pre-commit": [
    "lint"
  ],
  "pre-push": [
    "test"
  ]
}
`
![Screen Shot 2020-12-21 at 6 26 18 PM](https://user-images.githubusercontent.com/28362433/102823759-46754280-43ba-11eb-8bc3-28284fb4693d.png)

**Comment by martpie** [comment]
Please read the v5 changelog and the faq, the solution is described there.

**Comment by alexandregme** [comment]
if you are talking about the property on package.json
` "main": "./index.js",`

I have added there got into this error with is the same as v4

![Screen Shot 2020-12-21 at 7 21 27 PM](https://user-images.githubusercontent.com/28362433/102827689-cfdc4300-43c1-11eb-948d-b5c343c411c4.png)

I also have added an alias on the babel styleguide side.

babel.config.js

`module.exports = {
  presets: ['@babel/preset-env', '@babel/preset-react'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./'],
        components: './components',
      },
    ],
    ['inline-react-svg'],
  ],
};
`

**Comment by alexandregme** [comment]
Using the path to make it be resolved.
`
import { BLUE_100 } from '../../theme/colors.style';
import { LINE_HEIGHT } from '../../theme/typography.style';
`

`next-transpile-modules - transpiled: /Users/amendes/workpace/styleguide/page/node_modules/styleguide/components/theme/colors.style.js
next-transpile-modules - transpiled: /Users/amendes/workpace/styleguide/page/node_modules/palladium/components/theme/typography.style.js
error - ./node_modules/palladium/components/app/layout/layout.style.js
Attempted import error: 'createUseStyles' is not exported from 'react-jss'.
event - compiled successfully
`

this results on a 404 page.
