### ISSUE TITLE
`clean-stack` does not get transpiled

### ISSUE THREAD

**Issue by Algram** [martpie/next-transpile-modules#168]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
npm

**Describe the bug**
`clean-stack` does not get transpiled in a newly setup next project with `webpack 5`

**To Reproduce**
Check out this repo https://github.com/Algram/next-transpile-modules-reprod
The relevant code is in `pages/index.js`.

**Expected behavior**
`clean-stack` does get transpiled

**Setup**

- yarn build
- yarn start
- open in IE11

If you remove clean-stack from the repo above it works.

**Additional context**
Discussed previously here: https://github.com/martpie/next-transpile-modules/issues/147

**Comment by Algram** [comment]
I am not sure, but maybe the problem is also, that a sub dependency of `clean-stack` named `escape-string-regexp`.

If I add that to the transpile modules list it still shows the same error though, so in any case one of those two dependencies has a problem getting transpiled.

**Comment by martpie** [comment]
To be sure which package is causing an issue, you can use this strategy:

https://github.com/martpie/next-transpile-modules/issues/143#issuecomment-775977710

**Comment by Algram** [comment]
@martpie Ah thanks, that is really helpful.

I can say now, that `escape-string-regexp` is the offending package.

**Comment by martpie** [comment]
Is it still relevant?
