### ISSUE TITLE
How to handle module that don't have package.json or main field (because they don't need to)

### ISSUE THREAD

**Issue by MoOx** [martpie/next-transpile-modules#170]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**

I am trying to transpile `bs-platform`, and some `reason-*` packages.

**Describe the bug**

When starting next.js, this module crash with the following error:

```
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://err.sh/next.js/react-version
Error: next-transpile-modules - an unexpected error happened when trying to resolve "bs-platform"
Error: Can't resolve 'bs-platform' in '/Users/moox/dev/moox.io'
```

**To Reproduce**

Steps to reproduce the behavior (a reproduction is even better):

Just try to include `bs-platform`. ReScript works by compiling JS where the ReScript files are located. ReScript itself (bs-platform = ReScript Package) have a kind of standard lib that is built-in. 

**Expected behavior**

bs-platform don't need a package.json main field because you don't consume this directly. You only directly consume at some files. Yeah it's "all files" but they are only consumed individually by hitting directly them when included.

For example

<img width="772" alt="image" src="https://user-images.githubusercontent.com/157534/110158962-5792f480-7dea-11eb-831e-c7b89561a615.png">

**Setup**

- Next.js version: 10.0.8
- `next-transpile-modules` version: 6.3.0
- Node.js version: 10.22
- `npm`/`yarn` version: yarn v1.22.4
- Operating System: macOS
- Webpack 4 or 5: 4

**Additional context**

It was working with previous version of this module :(

**Comment by martpie** [comment]
The `main` field (or `exports` field) is a necessary thing in order for `enhanced-resolve` to get the root path of the package you are trying to transpile. 

It is not a constrain I am willing to remove, as this is what allowed fixing some otherwise unfixable issues (cf. #115).

I know it may not make sense for some really particular usecases where you never import anything from root, I personally believe this is still a good practice. This is also a small price to pay for something not included in vanilla next.js too.

**Comment by martpie** [comment]
sidenote: if you manage to find a way to may `enhanced-resolve` work the way you want, we can discuss it around a PR.

**Comment by MoOx** [comment]
What about letting people override `getPackageRootDirectory`? that cost nothing to this module & let people like me workaround this issue?

**Comment by martpie** [comment]
So how would you see yourself using this function exactly? for your problem in particular I mean.

**Comment by MoOx** [comment]
```js
const getPackageRootDirectory = (m) =>  path.resolve(path.join(__dirname, "node_modules", m));
```

I am using this already (I didn't patches your lib directly but extracted the logic instead) and it works perfectly in my case.

Full code here https://twitter.com/MoOx/status/1368313211695554566

**Comment by martpie** [comment]
Instead of giving the name of the package, try to target a file in your package. Example:

```require('next-transpile-modules')(['my-lib/some/module.js']);
```

The result should be equivalent. What matters is that `enhanced-resolve` can resolve to a module so it can identify the path of the package's `package.json`.

**Comment by MoOx** [comment]
Should the ['some-module/package.json'] be good enough? I tried but it doesn't seems to work.
And as I have many reps that can have generated js files, I don't really want to specify explicitly js file as they can change from version to version (and you know that I am lazy).

**Comment by MoOx** [comment]
Ok it seems to work using `package.json` after module name. I still have issues (so "nothing is working") but at least `packageRootDirectory` get filled with proper modules path. Investigating for the rest of the issue ("ReferenceError: Can't find variable: module")

**Comment by MoOx** [comment]
Ok so to track down the issue, it's working with module name+package.json with webpack 4, but as soon as I enable webpack 5, I get issue "ReferenceError: Can't find variable: module" on the first es6 module (eval in the browser). Trying to dig more about what is wrong with webpack 5 and this plugin (using latest version 6.4.0).

**Comment by martpie** [comment]
Can you try to target any JS file instead of `package.json`?

**Comment by martpie** [comment]
Also, if you can paste a debug log, that'd help 👍

**Comment by MoOx** [comment]
So I won't try other file as clearly, with debug: true, I see all the files I want to be transpiled.

Here is just an example

```
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/react-native-web/dist/cjs/index.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/react-native-web/dist/cjs/index.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/react-native-web/dist/cjs/index.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/react-native-web/dist/cjs/index.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/bs-platform/lib/es6/belt_Array.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/bs-platform/lib/es6/belt_Option.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/bs-platform/lib/es6/curry.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/bs-platform/lib/es6/belt_Array.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/bs-platform/lib/es6/caml_option.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/bs-platform/lib/es6/curry.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/bs-platform/lib/es6/caml_option.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/bs-platform/lib/es6/caml_option.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/react-native-web/dist/cjs/index.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/react-native-web/dist/cjs/index.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/react-native-web/dist/cjs/index.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/bs-platform/lib/es6/belt_Array.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/react-native-web/dist/cjs/index.js
next-transpile-modules - transpiled: /Users/moox/dev/dame.bio/node_modules/bs-platform/lib/es6/caml_option.js
```

So can this be related to webpack5 handling es6 import/export differently. bs-platform js code only have named export, no default export and I saw something about this could be an issue https://github.com/martpie/next-transpile-modules/issues/181

If you are curious, you can get this branch https://github.com/MoOx/dame.bio/tree/webpack5, `npm install && npm run dev` to reproduce (also open url in the browser)

**Comment by martpie** [comment]
Can you post the full log? The beginning is especially important

**Comment by martpie** [comment]
FYI everyone: https://github.com/martpie/next-transpile-modules/pull/202 should fix the problem.

Any feedback/test/confirmation it works as intended is very welcome!

**Comment by MoOx** [comment]
@martpie I still need to point to `{module}/package.json` with 7.0.0 (but no big deal)

**Comment by martpie** [comment]
You need to yet master, not v7, it has not been released yet ;)
