### ISSUE TITLE
React Version/Hook issue despite recommended config changes

### ISSUE THREAD

**Issue by PWesterdale** [martpie/next-transpile-modules#173]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
Local package

**Describe the bug**
When using npm link to link the component library/module any time the library uses a hook, you will recieve the react-hooks error.

**To Reproduce**
https://github.com/PWesterdale/next-transpile-issue

**Expected behavior**
It'd be super sweet if we didn't get a react error and it worked :)

**Setup**

Please see above repro case - if i can offer any more help let me know!

**Comment by martpie** [comment]
- Have you tried `file:/` instead of `link:/`?
- Is there any reason why you are not using workspaces (npm/yarn)?

**Comment by PWesterdale** [comment]
Hey martpie!

I've not tried file, I can give that a go just now and I've not used workspaces before, I'm tied into NPM in the business I work for at the moment, so a move to yarn is not going to be possible.

**Comment by PWesterdale** [comment]
I've just tried file, and I'll update my repro with the branch test-file, but it didn't help.

**Comment by martpie** [comment]
> so a move to yarn is not going to be possible.

npm `7.0` supports workspaces. This is definitely the easiest way to integrate local modules with `next-transpile-modules`.

I will try to have a look into it when I can.

**Comment by PWesterdale** [comment]
npm `7.0` has issues with fetching dependencies from private registries, so I'm also blocked on that front 😭 .
I think the problem I'm trying to solve is that we use our component library module via link only when we are developing, after that point it can be consumed by many different applications, so binding them together in workspaces may not be a valid solution for us.
I've pencilled some time in this weekend to look over it myself further, but past this point the errors from react/next get really quite nasty, I have dropped you an e-mail privately to discuss an option of some sponsorship as it would very much help me to get this project over the line.

**Comment by martpie** [comment]
Ok, can you try the following:

```tsx
const path = require('path');
const withTM = require('next-transpile-modules')(['test-library']);

module.exports = withTM({
  webpack: (config, options) => {
    if (options.isServer) {
      config.externals = ['react', ...config.externals];
    }

    config.resolve.alias['react'] = path.resolve(
      __dirname,
      '.',
      'node_modules',
      'react'
    );

    return config;
  },
});
```

**Comment by martpie** [comment]
Sidenote: if you cannot use workspaces, I would recommend using `file:/` as it makes things a bit more clear for your dependencies. But you might need to change things on your CI at some point.

Anyway, it's a detail.

**Comment by robbykurnia** [comment]
> Ok, can you try the following?
> 
> ```tsx
> const path = require('path');
> const withTM = require('next-transpile-modules')(['test-library']);
> 
> module.exports = withTM({
>   webpack: (config, options) => {
>     if (options.isServer) {
>       config.externals = ['react', ...config.externals];
>     }
> 
>     config.resolve.alias['react'] = path.resolve(
>       __dirname,
>       '.',
>       'node_modules',
>       'react'
>     );
> 
>     return config;
>   },
> });
> ```

thanks it worked, I had the same problem
