### ISSUE TITLE
Add tag & release notes for 6.3.0

### ISSUE THREAD

**Issue by mtlewis** [martpie/next-transpile-modules#175]
**Is your feature request related to a problem? Please describe.**
I notice that v6.3.0 has been released without a tag or release notes. This means that dependabot update PRs don't contain a description of the changes since the last version.

**Describe the solution you'd like**
Would be great to create a release from whatever commit 6.3.0 was published from! This should mean that new dependabot PRs correctly contain the changes since the last version. Thanks!

**Comment by martpie** [comment]
done
