### ISSUE TITLE
No HMR when (main) file(s) are siblings of package.json

### ISSUE THREAD

**Issue by philipbushnell-valtech** [martpie/next-transpile-modules#176]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
Local package.

**Describe the bug**
Fast refresh / hot reload / HMR not working in transpiled modules whilst it's working fine in the nextjs app. A site restart is needed to pick up changes.

**To Reproduce**
Monorepo solution using yarn workspaces with app/package structure:
```
root
  brands
    [brand name]
      apps
        shop (nextjs app)
  packages
    core
      button
        index.ts
        package.json (with main property linking to index.ts)
```

**Expected behavior**
Fast refresh / hot reload / HMR works like the nextjs app for linked local packages.

**Setup**
- Next.js version: 10.0.8 (though tried with 10.0.6 and 10.0.5 amongst others)
- `next-transpile-modules` version: 6.3.0 (though tried with 6.2.0)
- Node.js version: 12.16.1
- `yarn` version: 1.22.5
- Operating System: Windows 10 Pro
- Webpack 4 or 5: Not sure - whatever is default for `npx create-next-app [name]`

`root/package.json`:
```
{
  "name": "root",
  "private": true,
  "workspaces": [
    "brands/**",
    "packages/**"
  ],
  "dependencies": {
    ... (not next-transpile-modules)
  },
  "devDependencies": {
    ... (not next-transpile-modules)
  }
}
```

`root/brands/[brand name]/apps/shop/package.json`:
```
{
  "name": "@brandName/shop",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@company-core/button": "0.1.0",
    "next": "10.0.8",
    "react": "~17.0.1",
    "react-dom": "~17.0.1"
  },
  "devDependencies": {
    "@types/node": "^14.14.31",
    "@types/react": "~17.0.1",
    "next-transpile-modules": "6.3.0",
    "sass": "^1.32.8",
    "typescript": "^4.2.3"
  }
}
```

`root/lerna.json`:
```
{
  "npmClient": "yarn",
  "packages": ["packages/**"],
  "useWorkspaces": true,
  "version": "independent"
}
```

`root/.yarnrc`:
```
"@company-core:registry" "http://localhost:4873"
```

**Additional context (the original discussion)**
I've recently been working with others setting up a monorepo solution using yarn workspaces for `next` 10 (version 10.0.8 - latest at the point of writing) and using `next-transpile-modules` 6 (version 6.3.0 - latest at the point of writing). In the setup, we were having everything transpile as expected (following the readme) but found that fast refresh / hot reload / HMR wasn't working for changes inside yarn workspace linked packages outside of the nextjs app.

We had a structure like `root > packages > core > button` and inside this was the `package.json` and the package files (which I'll simplify to just `index.js`), and we had the main property pointing at `index.js`. What we found was that if we moved `index.js` into any folder (we used `src`) and updated main to point to the new location (now `src/index.js`), HMR started working as expected.

We haven't looked any further into this as it's all working but currently it seems like a "magic solution". Having a `src` folder is a convention anyway so we're happy to continue like this but there might be an assumption about the package folder structure somewhere?

I thought I'd post anyway to potentially save someone else some time and trouble, and to suggest that at the very least this is documented somewhere.

**Comment by martpie** [comment]
I've tested files at the root, and files as `index.js` at the root and HMR works fine with Yarn workspaces, can you follow the issue template please? https://github.com/martpie/next-transpile-modules/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by pbvt** [comment]
Sorry, I forgot the structure when I converted the discussion. It should be filled out now, plus I've kept the original discussion post in the additional context.

**Comment by martpie** [comment]
Are you using workspaces or Lerna? I am a bit confused right now 🤔 

Might be linked to #9

**Comment by pbvt** [comment]
It sounds like it could be related. I'm using yarn workspaces and lerna is just there for publishing (as is pointed out in the docs).
