### ISSUE TITLE
10.1.x compatibility

### ISSUE THREAD

**Issue by amala-james-cko** [martpie/next-transpile-modules#183]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**  : npm package
If an npm package, which one?
@amcharts/amcharts4/core,
@amcharts/amcharts4/maps,
@amcharts/amcharts4-geodata/worldLow

**Describe the bug**
Bug: SyntaxError: Unexpected token 'export' when upgraded Next.js to 10.1.2 with vercel serverless platform.
Logs: 
```
../node_modules/@amcharts/amcharts4/core.js:8
export { System, system } from "./.internal/core/System";
^^^^^^

SyntaxError: Unexpected token 'export'
```

**To Reproduce**
- Add amcharts in a next.js project and try to load the page where it is used.
- Example with code sandbox: https://codesandbox.io/s/amcharts-with-nextjs-xbf3g

**Expected behavior**
Expected no error on the terminal.

**Setup**

- Next.js version: 10.1.2
- `next-transpile-modules` version: 6.3.0
- Node.js version: 12.18.4
- `npm` version: 6.14.6
- Operating System: Mac OSX
- Webpack: 5

```
require("dotenv").config();
const redirects = require("../redirects");

//packages that are trying to transpile.
const withTM = require("next-transpile-modules")([
  "@amcharts/amcharts4/core",
  "@amcharts/amcharts4/maps",
  "@amcharts/amcharts4-geodata/worldLow",
]); // pass the modules you would like to see transpiled

const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
});

module.exports = withBundleAnalyzer({
  ...withTM(),
  compress: true
});

module.exports = {
  async redirects() {
    return redirects;
  },
};
```

**Additional context**
next-transpile-modules was working fine with next.js 10.0.0 and custom node server. This issue started when the project was migrated to next.js v10.1.2 and vercel serverless deployment platform.

**Comment by geisterfurz007** [comment]
For what it's worth, the latest supported Next.js version is 10.0.8: https://github.com/martpie/next-transpile-modules#compatibility-table

**Comment by martpie** [comment]
It looks like something broke indeed in 10.1.0.

I will try to see what happened.

cf. https://github.com/martpie/next-transpile-modules/pull/187

**Comment by martpie** [comment]
Seems to be related to Webpack 5 alone

**Comment by martpie** [comment]
Seems related to production builds.

**Comment by martpie** [comment]
@amala-james-cko can you check if it happens with the last version of this plugin and the last version of Next.js?

I had production build errors on 10.1.0 but they disappeared on 10.1.3. I suspect an issue with their experiment ESLint integration.

**Comment by amala-james-cko** [comment]
@martpie I still get the same error with Next.js 10.1.3 and next-transpile-modules 6.4.0.

**Comment by nandorojo** [comment]
I didn't know you could do two separate `module.exports`. Is that intentional?

**Comment by martpie** [comment]
Omg @nandorojo 😄

How did I miss that!?

**Comment by nandorojo** [comment]
I knew something felt off haha

**Comment by amala-james-cko** [comment]
@nandorojo Thank you for noticing it. That was the issue.
