### ISSUE TITLE
Out of memory issues with 6.4.0 and future: { webpack5: true }

### ISSUE THREAD

**Issue by kennandavison** [martpie/next-transpile-modules#184]
Hey there, thanks for the great work on this package! 

I upgraded to 6.4.0 and set future: { webpack5: true } in next.config.js this morning and got some OOM issues when next building in my CI/CD pipeline. Reverted and issue went away.

Has anyone else seen this as well?

**Comment by martpie** [comment]
Thank you very much for the report, can you follow the issue template and add some information like your CI provider or anything that could help debug it?

It's most probably related to what was done in https://github.com/martpie/next-transpile-modules/pull/179 by @sokra

I'll try to look into it whenever I can

**Comment by sokra** [comment]
> I upgraded to 6.4.0 and set future: { webpack5: true } in next.config.js

Did you change both at the same time, or step by step? This sounds more like an webpack 5 issue than related to next-transpile-modules.

**Comment by martpie** [comment]
I will re-open once the issue template will be followed. I can't act on anything right now.
