### ISSUE TITLE
Nested `node_modules` don't transpile

### ISSUE THREAD

**Issue by nandorojo** [martpie/next-transpile-modules#188]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**

npm package: `moti`.

I also want to transpile `moti`'s dependency: `@motify/core`

**Describe the bug**

v6.1.0 got rid of transpiling nested node modules. `@motify/core` is a nested node module of `moti`, so it is no longer transpiled. (At least that's what I think the cause is.)

**To Reproduce**

Here is the reproduction: https://github.com/nandorojo/transpile-modules-bug

- `yarn install`
- `yarn next`

Open `pages/index.js` and comment `MotiView` in / out. When it's not there, the app works fine.

<img width="726" alt="Screen Shot 2021-04-12 at 1 18 09 PM" src="https://user-images.githubusercontent.com/13172299/114434919-90647d00-9b91-11eb-9072-12c9fb9bae06.png">

However, if you include it, you'll see this error:

<img width="1072" alt="Screen Shot 2021-04-12 at 1 03 47 PM" src="https://user-images.githubusercontent.com/13172299/114433655-1253a680-9b90-11eb-9ad5-8dcf9bf41479.png">

I assume that this is due to the fact that `@motify/core` is a dependency of `moti`? `@motify/core` does have a `main` field in `package.json`, following the required spec.

**Expected behavior**

I expect `@motify/core` to transpile. However, in both my monorepo and reproduction, it doesn't.

Perhaps I need a way to transpile nested node modules? I'm fine with explicitly mentioning them if needed.

**Setup**

- Next.js version: `10.1.4-canary.2` – I have the same issue with latest (`10.1.3`) as well as `10.0.x`
- `next-transpile-modules` version: `6.4.0` (bug occurs with anything 6.1.0+)
- Node.js version: `v14.15.5`
- `yarn` version: `1.22.5`
- Operating System: macOS
- Webpack 4 or 5: 4

```js
// next.config.js
const { withExpo } = require("@expo/next-adapter");

const withTM = require("next-transpile-modules")([
  "moti",
  "@motify/core",
  "@motify/components",
]);

const withPlugins = require("next-compose-plugins");

module.exports = withPlugins([
  withTM,
  [
    withExpo,
    {
      projectRoot: __dirname,
    },
  ],
]);
```

I'm using React Native Web if that helps.

**Additional context**

The changelog says that 6.1.0 got rid of nested node_modules transpilation. My hunch is that this is related. However, when I don't install this package in a monorepo, `@motify/core` installs directly in my `node_modules` folder. So it's unclear to me why it isn't working. 

It does work with 6.0.0, but the app startup is far slower, so I'd prefer to use the newer version if possible.

I also thought it might be due to using Next.js 10.1.x, but the same issue happens with 10.0.x.

Thanks!

**Comment by martpie** [comment]
> @motify/core is a nested node module of moti, so it is no longer transpiled.

So it depends. Sometimes dependencies of dependencies are saved at the same level than your dependencies. You'd have to go to `node_modules` and try to figure out where `@motify/core` is.

Theoretically, if `@motify/core` is under `moti`. `require('next-transpile-modules')(['moti', 'moti/node_modules/@motify/core'])` should make it work.

**Comment by nandorojo** [comment]
Right, that makes sense. 

In both my reproduction and monorepo, I see it in the root node_modules:

<img width="427" alt="Screen Shot 2021-04-12 at 1 53 52 PM" src="https://user-images.githubusercontent.com/13172299/114439060-8d1fc000-9b96-11eb-9a1f-b290a57dc760.png">

Which makes the think it should transpile.

However, the stack trace for my monorepo shows it nested inside of `moti`. Like you suggested, I tried adding `'moti/node_modules/@motify/core'` there, but not luck.

This is the stack trace for my monorepo, where, unlike the reproduction I linked to, it shows that it's a truly nested node module.

<img width="1103" alt="Screen Shot 2021-04-11 at 11 38 15 PM" src="https://user-images.githubusercontent.com/13172299/114439161-af194280-9b96-11eb-99c4-76e22855db46.png">

**Comment by nandorojo** [comment]
I checked in the finder, and for my monorepo, it does indeed install `@motify/core` as a nested node module:

<img width="344" alt="Screen Shot 2021-04-12 at 1 58 33 PM" src="https://user-images.githubusercontent.com/13172299/114439723-4c747680-9b97-11eb-9932-5d4556be5c89.png">

So I'm not entirely sure why adding `'moti/node_modules/@motify/core'` doesn't solve it.

That said, `@motify/core` is _not_ nested inside of `moti/node_modules` in the reproduction I shared.

**Comment by martpie** [comment]
Can you enable the debug mode and paste the logs here?

**Comment by nandorojo** [comment]
```sh
next-transpile-modules - the following paths will get transpiled:
  - /Users/fernandorojo/Developer/os/transpile-bug/node_modules/moti
  - /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core
  - /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/components
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/moti/lib/commonjs/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/moti/lib/module/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/components/lib/commonjs/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/components/lib/module/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/motify.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/types.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/use-map-animate-to-style.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/motify.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/types.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/use-map-animate-to-style.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/use-animator/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/use-dynamic-animation/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/constants/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/use-map-animate-to-style.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/use-animator/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/use-dynamic-animation/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/constants/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/use-map-animate-to-style.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/constants/package-name.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/constants/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/constants/package-name.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/constants/package-name.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/constants/package-name.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/constants/index.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/commonjs/constants/color-keys.js
next-transpile-modules - transpiled: /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core/lib/module/constants/color-keys.js
```

**Comment by martpie** [comment]
Well that looks quite good to me.

Have you tried that? https://github.com/martpie/next-transpile-modules#how-do-i-find-out-which-package-is-causing-a-runtime-exception

**Comment by nandorojo** [comment]
> Well that looks quite good to me.

Agreed, which is why I'm a bit confused by it.

> Have you tried that? https://github.com/martpie/next-transpile-modules#how-do-i-find-out-which-package-is-causing-a-runtime-exception

Yeah, the build failed at the same step.

```js
// next.config.js

const { withExpo } = require("@expo/next-adapter");

const withTM = require("next-transpile-modules")(
  ["moti", "@motify/core", "@motify/components"],
  { debug: true }
);

const withPlugins = require("next-compose-plugins");

module.exports = withPlugins([
  withTM,
  [
    withExpo,
    {
      projectRoot: __dirname,
      webpack: (config) => {
        config.optimization.minimize = false;
        return config;
      },
    },
  ],
]);
```

And then running `next build`:

```sh
$ next build
warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://nextjs.org/docs/messages/react-version
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
next-transpile-modules - the following paths will get transpiled:
  - /Users/fernandorojo/Developer/os/transpile-bug/node_modules/moti
  - /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core
  - /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/components
info  - Checking validity of types .next-transpile-modules - the following paths will get transpiled:
  - /Users/fernandorojo/Developer/os/transpile-bug/node_modules/moti
  - /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/core
  - /Users/fernandorojo/Developer/os/transpile-bug/node_modules/@motify/components
info  - Checking validity of types  
warn  - Production code optimization has been disabled in your project. Read more: https://nextjs.org/docs/messages/minification-disabled
info  - Using external babel configuration from /Users/fernandorojo/Developer/os/transpile-bug/babel.config.js
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[=== ] info  - Generating static pages (0/3)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at useAnimatedStyle (/Users/fernandorojo/Developer/os/transpile-bug/.next/server/pages/index.js:1882:18433)
    at useMapAnimateToStyle (/Users/fernandorojo/Developer/os/transpile-bug/.next/server/pages/index.js:2196:17041)
    at Object.Wrapped [as render] (/Users/fernandorojo/Developer/os/transpile-bug/.next/server/pages/index.js:1990:2317)
    at a.b.render (/Users/fernandorojo/Developer/os/transpile-bug/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:46:105)
    at a.b.read (/Users/fernandorojo/Developer/os/transpile-bug/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/Users/fernandorojo/Developer/os/transpile-bug/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at renderPage (/Users/fernandorojo/Developer/os/transpile-bug/node_modules/next/dist/next-server/server/render.js:54:854)
    at _callee$ (/Users/fernandorojo/Developer/os/transpile-bug/.next/server/pages/_document.js:308:3286)
    at tryCatch (/Users/fernandorojo/Developer/os/transpile-bug/node_modules/regenerator-runtime/runtime.js:63:40)
info  - Generating static pages (3/3)

> Build error occurred
Error: Export encountered errors on following paths:
        /
    at /Users/fernandorojo/Developer/os/transpile-bug/node_modules/next/dist/export/index.js:31:1106
    at async Span.traceAsyncFn (/Users/fernandorojo/Developer/os/transpile-bug/node_modules/next/dist/telemetry/trace/trace.js:5:584)
    at async /Users/fernandorojo/Developer/os/transpile-bug/node_modules/next/dist/build/index.js:43:49
    at async Span.traceAsyncFn (/Users/fernandorojo/Developer/os/transpile-bug/node_modules/next/dist/telemetry/trace/trace.js:5:584)
    at async /Users/fernandorojo/Developer/os/transpile-bug/node_modules/next/dist/build/index.js:25:1475
    at async Span.traceAsyncFn (/Users/fernandorojo/Developer/os/transpile-bug/node_modules/next/dist/telemetry/trace/trace.js:5:584)
error Command failed with exit code 1.
```

I know exactly which line is failing in `@motify/core`. Its failure mimicks what would happen in `react-native-reanimated`'s babel plugin weren't applied to it. This is the babel config:

```js
module.exports = function (api) {
  api.cache(true);

  return {
    presets: ["@expo/next-adapter/babel"],
    plugins: [
      "react-native-reanimated/plugin", // this plugin is what's needed
      "@babel/plugin-proposal-class-properties",
    ],
  };
};
```

**Comment by nandorojo** [comment]
One thing I have noticed from using `debug: true` is that the same file gets transpiled multiple times. Is this intended? For example, try `command + f` the following:

@motify/core/lib/commonjs/index.js

Notice that in the `debug` trace above, it shows up multiple times. In my large monorepo, this seems to take up some time. It's perhaps unrelated to this issue, so let me know if I should open it in a separate issue.

**Comment by nandorojo** [comment]
I've run some additional tests:

**This works:**

```js
import { MotiView } from '@motify/components'
```

**This does not:**

```js
import { MotiView } from 'moti'
```

FWIW, I'm the maintainer of `moti`. 

This is the `moti` source file:

```ts
// index.tsx
export * from '@motify/core'
export * from '@motify/components'
```

## Hypothesis

@martpie can you think of any reason that re-exporting using `*` for an entire library could be causing this? I can't seem to think of anything else.

The component I want to use is from `@motify/components`. 

`@motify/components` imports `@motify/core`, builds the component, and exports it. Then `moti` exports everything from  both.

## Added context

These all work:

```js
import { MotiView } from '@motify/components'
import { MotiView } from '@motify/components/src'
import { MotiView } from '@motify/components/lib/module'
import { MotiView } from '@motify/components/lib/commonjs'
```

None of the equivalent ones imported directly from `moti` work.

**Comment by martpie** [comment]
I'd need to invest some time and try to reproduce the issue locally, there's a lot of information to be processed :smile:

**Comment by nandorojo** [comment]
Yeah sorry about that haha. Just wanted to be thorough. Let me know if I can be of use.

**Comment by martpie** [comment]
Will be released soon.
