### ISSUE TITLE
Support for scopes

### ISSUE THREAD

**Issue by paales** [martpie/next-transpile-modules#189]
**Is your feature request related to a problem? Please describe.**
Automatic support for workspaces

**Describe the solution you'd like**

```typescript
import { execSync } from 'child_process'
import { createHash } from 'crypto'
import { readFileSync, writeFileSync } from 'fs'
import withTranspileModules from 'next-transpile-modules'

import { PackageJson } from 'type-fest'

export type WorkspaceInfo = {
  [name: string]: {
    location: string
    workspaceDependencies: string[]
    mismatchedWorkspaceDependencies: string[]
  }
}

export function withYarn1Workspaces(modules: string[] = []) {
  const packageStr = readFileSync('package.json', 'utf-8')
  const packageJson = JSON.parse(packageStr) as PackageJson

  const hashSum = createHash('sha256').update(packageStr, 'utf-8').digest('hex').slice(0, 10)

  let infoJson: string
  const cacheKey = `.next/cache/withYarn1Workspaces.${hashSum}.json`
  try {
    infoJson = readFileSync(cacheKey, 'utf-8')
  } catch (e) {
    infoJson = execSync('yarn workspaces info --json', { encoding: 'utf-8' })
    try {
      writeFileSync(cacheKey, infoJson)
    } catch (er) {
      // do nothing
    }
  }

  const workspaceInfo = JSON.parse(JSON.parse(infoJson).data) as WorkspaceInfo

  const requestedPackages = [
    ...Object.keys(packageJson.dependencies ?? {}),
    ...Object.keys(packageJson.devDependencies ?? {}),
  ]

  const entries = Object.entries((workspaceInfo as unknown) as WorkspaceInfo)

  const m = new Set<string>(modules)
  entries.forEach(([p, b]) => {
    if (requestedPackages.includes(p)) {
      m.add(p)
      b.workspaceDependencies.forEach((wp) => m.add(wp))
    }
  })

  return withTranspileModules([...m.values()], { resolveSymlinks: true })
}
```

**Comment by martpie** [comment]
So the idea is to transpile every package under a `@scope`?

**Comment by paales** [comment]
Yeah, exactly :)

**Comment by timakhalaya** [comment]
since next-transpile-modules is not working properly with scoped packages.
what would be a proper way to use it 
`const withTM = require('next-transpile-modules')([
    '@cloud/*',
    'react-children-utilities'
])`
with the above it just doesnt load :/ 
any help would be appreciated

**Comment by martpie** [comment]
You have to explicit list all you scoped packages for now.

`['@scope/package-a', '@scope/package-b', , '@scope/package-c']`

Etc.

**Comment by timakhalaya** [comment]
Will write a parser function for it

**Comment by martpie** [comment]
The problem is not making it work for one setup, but for all setups. The actual code for scoped packages can be located from anywhere from the root of the Next.js app to the root of the git repository, depending on where your package manager decides to place them. 

This is the real problem to tackle, and why it is not included by default in `next-transpile-modules`. :)
