### ISSUE TITLE
Can experimental feature from Next.js 'externalDir' replace this plugin completely or do we still need it?

### ISSUE THREAD

**Issue by matiishyn** [martpie/next-transpile-modules#203]
I'm sorry I don't keep the format, but this is just a question hopefully in the right place

I've just scrolled down to this comment
https://github.com/vercel/next.js/issues/9474#issuecomment-810212174
and looks like it should do the job.
So, my question is, Can this replace the `externalDir` replace the `next-transpile-modules` plugin completely or do we still need it?

**Comment by martpie** [comment]
I saw this new thing in a next.js commit, but I did not investigate more than that, so the answer is: idk.

I may replace common scenarios like transpiring a module for IE11, but I don't think it'll cover things like transpiling CSS or enabling HMR, but this is just me speculating.

**Comment by donsn** [comment]
> I saw this new thing in a next.js commit, but I did not investigate more than that, so the answer is: idk.
> 
> It may replace common scenarios like transpiling a module for IE11 or dealing with monorepos, but I don't think it'll cover things like transpiling CSS or enabling HMR, but this is just me speculating.

It supports HMR. But I'll use this till 'externalDir' is no longer an experimental feature
