### ISSUE TITLE
Unwanted deprecation warnings for next/head, next/router, and styled-jsx/server

### ISSUE THREAD

**Issue by martpie** [martpie/next-transpile-modules#208]
Some people are facing weird logs/warning like:

```
next-transpile-modules - DEPRECATED - fallbacking to previous module resolution system for module "next/head", you can now just pass the name of the package to transpile and it will detect its real path without you having to pass a sub-module.
next-transpile-modules - DEPRECATED - fallbacking to previous module resolution system for module "next/router", you can now just pass the name of the package to transpile and it will detect its real path without you having to pass a sub-module.
next-transpile-modules - DEPRECATED - fallbacking to previous module resolution system for module "styled-jsx/server", you can now just pass the name of the package to transpile and it will detect its real path without you having to pass a sub-module.
```

This is definitely a bug, as those deps are not used to initialize `next-transpile-modules`.

I think those warnings can be ignored, and I will work on a fix as soon as I find the root of the issue.

**Comment by martpie** [comment]
To anyone facing this bug, can you please fill this information? https://github.com/martpie/next-transpile-modules/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

It would greatly help 🙌

**Comment by efeminella** [comment]
I'm having the same issue. It's should be easy to reproduce by deleting yarn.lock, reinstalling dependencies, then starting next. 

I'm seeing the console continually flooded with DEPRECATION warnings:

next-transpile-modules - DEPRECATED - fallbacking to previous module resolution system for module "react/jsx-dev-runtime", you can now just pass the name of the package to transpile and it will detect its real path without you having to pass a sub-module.
next-transpile-modules - DEPRECATED - fallbacking to previous module resolution system for module "react/jsx-dev-runtime", you can now just pass the name of the package to transpile and it will detect its real path without you having to pass a sub-module.
next-transpile-modules - DEPRECATED - fallbacking to previous module resolution system for module "react/jsx-dev-runtime", you can now just pass the name of the package to transpile and it will detect its real path without you having to pass a sub-module.

**Comment by martpie** [comment]
@efeminella this message was introduced in 7.1.0, are you using 7.1.0 or 7.1.1?

**Comment by styxlab** [comment]
I am seeing these messages with `7.1.1`.

**Comment by efeminella** [comment]
@martpie - I am seeing this in both 7.1.0 and 7.1.1. Interestingly, a newly added local package can not be resolved in 7.0.0, but will resolve in 7.1.0 and 7.1.1, however, in both of the later, the `next-transpile-modules - DEPRECATED - fallbacking to previous module resolution system for module` message is displayed (though the newly added package resolves as expected.

Also, any thoughts as to why the newly added package would not resolve in 7.0.0 (it's simply a local package in our monorepo which is structured and configured exactly the same as all other packages)?

**Comment by martpie** [comment]
Ok, I can reproduce it on a Webpack 4 setup, I will investigate this more in details.

**Comment by martpie** [comment]
Should be fixed in 7.1.2.

**Comment by SimenB** [comment]
Warning is gone, thanks!

**Comment by martpie** [comment]
Thank you for confirming! ✌️
