### ISSUE TITLE
⚡️ How do you import/export transpiled modules from the root index.js without having a huge bundle size?

### ISSUE THREAD

**Issue by altechzilla** [martpie/next-transpile-modules#211]
- [X] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [X] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
Local Package

**Describe the bug**
We're working on modules that have dozens of components. Since we're transpiling them, we have to reference their exact path when importing them to the main app. How can we create a "map" of components in the index.js file without importing/exporting every module for every single page?

**To Reproduce**
For example, in one of our app components we import the following:

```
import Row from '@destacked/interface/components/layout/Row';
import Column from '@destacked/interface/components/layout/Column';
import Button from '@destacked/interface/components/elements/Button';
import Shader from '@destacked/interface/components/elements/Shader';
import Icon from '@destacked/interface/components/elements/Icon';
```

Instead, we would want to import them like this:
```
import { Row, Column, Button, Shader, Icon } from '@destacked/interface';
```

If we do that, we'll have to import/export them in the main @destacked/interface index.js file.

However, instead of only importing them on the right pages, the entire bundle size will include every single component.

**Expected behavior**
Looking for a way to "map" those components, similar to how you do in `jsconfig.json`, without having to create a `jsconfig.json` for every single app individually. Is there a way to either include some sort of jsconfig.json inside each module, or run a script that builds the module for production instead of transpiling it?

**Setup**
- Next.js version: 10.2.2
- `next-transpile-modules` version: 7.2.0
- Node.js version: 12.18.3
- `npm`/`yarn` version: 7.7.5
- Operating System: macOS
- Webpack 4 or 5: 5

**next.config.js**
```
const withPlugins = require('next-compose-plugins');

/**
 * Transpile Modules
 */

const withTM = require('next-transpile-modules')(
    [
        '@destacked/core',
        '@destacked/interface',
        '@destacked/blocks'
    ],
    {
        resolveSymlinks: false,
    }
);

module.exports = withPlugins([withTM], config);
```

**Additional context**
As explained above. Thank you!

**Comment by alexandre-marchina** [comment]
Perhaps you could put `"sideEffects": false` inside the `package.json` from that shared module. 
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

We've managed to do that in a similar scenario, but we're not using the newest versions (we're using 7.0.0 and webpack 4)

**Comment by martpie** [comment]
This is Webpack's responsibility to do tree-shaking correctly, [a little bit like Parcel v2 is doing](https://v2.parceljs.org/blog/beta3/#tree-shaking-dynamic-import), not `next-transpile-modules`.

From what I remember, and using a big `index.ts` with a lot of `export * from '...'`, Webpack was doing a great job placing in the bundle only the components I was using, but I am not 100% certain, it was a while ago.

**Comment by martpie** [comment]
> However, instead of only importing them on the right pages, the entire bundle size will include every single component.

Have you verified this assumption with a production build and [`@next/bundle-analyzer`](https://www.npmjs.com/package/@next/bundle-analyzer)?
