### ISSUE TITLE
Tailwind CSS is not included in consumer package only for production build.

### ISSUE THREAD

**Issue by fawwaz** [martpie/next-transpile-modules#212]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?** 
If an npm package, which one?
Local Package

**Describe the bug**
A clear and concise description of what the bug is (don't forget the logs if applicable).
I created a monorepo setup using lerna. I plan to have 2 packages: 
```
.
└── packages
    ├── web-app (consumer)
    └── web-ui (using tailwind)
```
When I run web-app for development mode, (`yarn dev`) the tailwind styling is applied (the component that is located within web-ui is styled correctly). However, when I run for production build (`yarn build`) the tailwind styling is missing (I guess it is purged (?))
|  yarn dev  | yarn build  |
|---|---|
| ![Screenshot from 2021-05-27 11-10-06](https://user-images.githubusercontent.com/1295143/119766478-46d0b700-bedf-11eb-81a0-7d20e36713a1.png)  | ![Screenshot from 2021-05-27 11-08-52](https://user-images.githubusercontent.com/1295143/119766436-34567d80-bedf-11eb-8006-8cde834977f9.png)  |

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):
1. Clone this repository : https://github.com/fawwaz/next-transpile-modules-issue
2. Run yarn install in the root folder
3. Run yarn build in `packages/web-app`
4. Run yarn start in `packages/web-app` 

**Expected behavior**

Running production build should include the tailwind styling.

**Setup**

- Next.js version: 10.2.3
- `next-transpile-modules` version: 7.2.0
- Node.js version: 14.6.1
- `npm`/`yarn` version:  1.22.10
- Operating System: Linux (Ubuntu 20.04)
- Webpack 4 or 5: 4 (version : 4.46.0)

**Additional context**

**Comment by martpie** [comment]
Have you tried disabling purge completely to see if it would make it work? Because it looks more like an issue in your setup than an issue with ntm.

**Comment by fawwaz** [comment]
I tried. Yes, removing purge option loads the entire CSS, but it also means the objective of purge CSS is not achieved as it also loads any irrelevant CSS rules. 

I think I should rephrase the question : how can I set the webpack option(purge CSS option) so it will purge the CSS from local module ?

**Comment by martpie** [comment]
Well then it's not exactly related to `next-transpile-modules`, it's really just about applying purge to your packages in `node_modules`.

If I had to look somewhere, I'd check your tailwind config and add a glob there:

https://github.com/fawwaz/next-transpile-modules-issue/blob/master/packages/web-app/tailwind.config.js

```
purge: [
  "./pages/**/*.{js.ts,tsx,jsx}",
  "./components/**/*.{js.ts,tsx,jsx}",
  "web-ui/**/*.{js.ts,tsx,jsx}"]
```

No idea if it will work, but you can play with `require.resolve` to get the path to your package as well, but it's definitely where it can be fixed.
