### ISSUE TITLE
allow setting isWebpack5 via option (to work with current next@canary)

### ISSUE THREAD

**Issue by stefanprobst** [martpie/next-transpile-modules#215]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
n/a

**Describe the bug**
In the current canary version 10.2.4-canary.9, next disallows the `future.webpack5` option in `next.config.js`, which means i cannot tell `next-transpile-modules` to use webpack5, even though next is using it.

![Screenshot_20210609_155039](https://user-images.githubusercontent.com/20753323/121367270-76011280-c93a-11eb-9263-2a39d098ba51.png)

Possible solution could be to allow programmatically passing a `webpack5?: boolean` option to `next-transpile-modules`, which will be checked [here](https://github.com/martpie/next-transpile-modules/blob/9dbd4fef8821dc25a3e9044dc2cdb53ac69177df/src/next-transpile-modules.js#L91).

**To Reproduce**

**Expected behavior**

**Setup**

- Next.js version:
- `next-transpile-modules` version:
- Node.js version:
- `npm`/`yarn` version:
- Operating System:
- Webpack 4 or 5:

**Additional context**

**Comment by martpie** [comment]
Hello 👋 

Thanks for the report! I guess if they removed the flag, it's because they are going to remove Webpack 4 support (I need to double check that), so this "isWepback5" would not be extremely useful.

Can you tell me more about your usecase?

**Comment by stefanprobst** [comment]
apparently it's now a toplevel flag (i.e. not in `future` anymore)

my usecase is just transpiling a package, and i wanted to try out the new next canary, which threw the error in the image above with `next dev`.

**Comment by martpie** [comment]
I will add support for top-level `webpack5`, should be quite trivial.

**Comment by martpie** [comment]
Should be fixed in 7.3.0 👍

**Comment by stefanprobst** [comment]
thanks!

for documentation: `webpack5` needs to be explicitly set to `true` (even though that's the default):
```js
// next.config.js
const config = {
  /** @ts-expect-error */
  webpack5: true,
}
```

**Comment by martpie** [comment]
I will update the docs when it is official :)

**Comment by CalebDelbridge** [comment]
@martpie Webpack 5 now is the default in NextJS 11

**Comment by martpie** [comment]
Yep exactly, this is what I was waiting for, see #218 :)
