### ISSUE TITLE
issue with typescript in transpileModules

### ISSUE THREAD

**Issue by chrisdrackett** [martpie/next-transpile-modules#22]
I've recently been migrating my app from flow to typescript. I'm running into an issue where it seems that the typescript in one of the packages in my mono repo isn't correctly stripped out. Here is an example repo:

https://github.com/tiltshift/monoWorkspaces/tree/typescript

The error I get is:

```
ModuleBuildError: Module build failed (from ../node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
SyntaxError: /Users/cwd/src/monoWorkspaces/node_modules/@custom/core/components/Test.tsx: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (3:8):

  1 | import React from "react";
  2 |
> 3 | export interface testProps {
    |        ^
  4 |   text: string;
  5 | }
  6 |

Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.
```

my understanding is this code should not even be there by the time next gets to running it.

Sorry if I'm missing something basic, I'm pretty new to some of these tools!

**Comment by chrisdrackett** [comment]
ok, update!

I got this working by moving from using a `.babelrc` to a `babel.config.js`. I wonder if this is worth noting in the docs?

https://github.com/tiltshift/monoWorkspaces/commit/d616778122ea9018d6289f618b9509a2234efbf0

**Comment by martpie** [comment]
Mmmh, maybe I should update the doc indeed. Babel configuration pickup is still a mystery to me.

I'll dive more in their docs.

Can it be closed then?

**Comment by TxHawks** [comment]
As far as I understand it, the resolution of config files is that `babel.config.js`is considered a project-wide config-file, meaning it is based on the root dir of the project, and therefore, can also apply to files in `node_modules` or symlinked files.

`.babelrc` and `.babelrc.js` are loaded relative to the file being transpiled, with traversal up the tree, in a similar fashion to how node resolves modules from `node_modules`. If more than one file-relative configs are resolved in the traversal, they are merged.

Do you think it would be a good idea to add an `examples` dir?

**Comment by martpie** [comment]
> Do you think it would be a good idea to add an `examples` dir?

Yes and no. I am thinking about how I could write tests for this plugin (and they could be used as examples), but it's quite hard. I do not think we need pure example, because everyone is opening issues here with so many different setup that it is impossible to cover them all.

What I can do is update the FAQ though. And I could also add a couple of boilerplates / examples from the main Next.js project in the README.

**Comment by chrisdrackett** [comment]
@martpie I think this can be closed, unless you want to keep it open as a reminder to add docs. I could take a crack as well, but I'd also need to understand the problem better. Thanks for the extra info @TxHawks!

**Comment by martpie** [comment]
Does this make sense to you @chrisdrackett? https://github.com/martpie/next-transpile-modules/commit/3f7dad2ad40e489f6a6ec1ddb1537001672cdceb

**Comment by matteoferigo** [comment]
> ok, update!
> 
> I got this working by moving from using a `.babelrc` to a `babel.config.js`. I wonder if this is worth noting in the docs?
> 
> [tiltshift/monoWorkspaces@d616778](https://github.com/tiltshift/monoWorkspaces/commit/d616778122ea9018d6289f618b9509a2234efbf0)

Thanks, I spent the whole noon to find the answer. Now this awesome plugin works again!!!

**Comment by martpie** [comment]
The FAQ is quite complete now, don't hesitate to have a look at it ;)
