### ISSUE TITLE
Getting an error with @graphql-tools/utils package

### ISSUE THREAD

**Issue by meliborn** [martpie/next-transpile-modules#221]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
@graphql-tools/utils

**Describe the bug**
I'm trying to transpile @graphql-tools/utils package, but getting 
```
./node_modules/@graphql-tools/utils/index.cjs.js
Module not found: Can't resolve '../../../graphql' in '/Users/den/Documents/Sites/RestaFE/node_modules/@graphql-tools/utils'
```

**To Reproduce**
`yarn add @graphql-tools`
`const withTM = require('next-transpile-modules')(['@graphql-tools/utils']);`

**Expected behavior**
It should transpile package without any errors

**Setup**

- Next.js version: 10.2
- `next-transpile-modules` version: 8.0.0
- Node.js version: 15
- `npm`/`yarn` version: yarn 1.22.10
- Operating System: Mac OX
- Webpack 5

My next.config.js:
```javascript
module.exports = withBundleAnalyzer(
	withSentryConfig(
		withOptimizedImages(
			withTM({
				defaultLocale: 'ru-Ru',
				poweredByHeader: false,
				async rewrites() {
					return rewrites;
				},
				reactStrictMode: true,
				future: {
					webpack5: true,
				},
				i18n,
				webpack(config) {
					config.plugins.push(new webpack.EnvironmentPlugin(localEnv));
					// Here is the magic
					// We push our config into the resolve.modules array
					config.resolve.modules.push(path.resolve('./'));

					return config;
				},
			}),
		),
	),
);
```

**Comment by martpie** [comment]
Please complete the issue template by checking the checkboxes and providing the Next version

**Comment by meliborn** [comment]
@martpie done

**Comment by martpie** [comment]
Please check the compatibility table, you're using the wrong version of the plug-in

**Comment by meliborn** [comment]
@martpie I've updated next to v11, but getting the same error:
![Снимок экрана 2021-06-27 в 02 06 46](https://user-images.githubusercontent.com/735194/123527943-544eac00-d6ec-11eb-8e19-dd81b10bb05f.png)
