### ISSUE TITLE
Safari - SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by tbutcaru-gpsw** [martpie/next-transpile-modules#228]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [ ] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
Local packages

**Describe the bug**
Running the NextJS app in production mode on Safari results in the following error:
![image](https://user-images.githubusercontent.com/28919585/128981037-23ae9d1d-c0af-4d7d-94af-30b915f41b95.png)
 

**To Reproduce**
Build a monorepo app using yarn workspaces and run it in production mode on Safari browser.

**Expected behavior**
Safari should work the same as Chrome, no console errors.

**Setup**

- Next.js version:
- `next-transpile-modules` version: 8.0.0
- Node.js version: 11.0.1
- `npm`/`yarn` version: 6.14.10 / 2.4.2
- Operating System: Mac Big Sur
- Webpack 4 or 5: 4

**Additional context**
Tested version ^7.0.0 of next-transpile-modules with next v11.0.1 and the issue no longer occurs, but v7.x.x is not officially compatible with next11.

**Comment by martpie** [comment]
Sorry I am not providing support for people who don't check both checkboxes.
