### ISSUE TITLE
Doesn't work for modules using `babel-plugin-module-resolver`

### ISSUE THREAD

**Issue by papermana** [martpie/next-transpile-modules#23]
I have two repos, both using `babel-plugin-module-resolver` for absolute paths in import, and one of them imports the other one. When trying to build the main app, I get a bunch of errors like:
> Module not found: Error: Can't resolve '../../../src/apiRoutes' in [path to location in node_modules]

What is curious here, is that it tries to resolve `src/apiRoutes` in our imported package to a location in the project that imports it.
```
my-project
 |- src
     |- bunch of stuff
 |- node_modules
     |- foo
         |- apiRoutes
```

Or, in other words, it uses my local Babel config when transpiling the package from `node_modules`, because both have `src` as one of the aliases used in absolute paths.

This is clearly problematic for this use case. But if my explanation is correct, then I could also foresee problems in other situations, like when package X relies on an experimental language feature which package Y doesn't use, and when you import X into Y, the app breaks because Y's Babel config doesn't know how to transpile it.

**Comment by papermana** [comment]
This issue might be related to what [this comment](https://github.com/martpie/next-transpile-modules/issues/22#issuecomment-467786111) says. But when I checked `babel.config.js` to `.babelrc.js` in both repos, it seems that it still doesn't use the local Babel config. Now it just doesn't resolve aliases at all for the imported package.

**Comment by TxHawks** [comment]
I think that's not how it works. To the best of my understanding, if you transpile packages, you need to provide all the Babel settings, plugins, presets, etc. that are needed to transpile you packages. I think that's just how Babel works.

**Comment by martpie** [comment]
Let's close this in favor of #21 :)

I am in holidays but I will investigate this issue this week-end
