### ISSUE TITLE
Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by devv-aman** [martpie/next-transpile-modules#230]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
If an npm package, which one?
```react-transpile-modules```

**Describe the bug**
We're building our next project on AWS ECS with build CPU size of 3GB
Things have been running smooth, although since last deploy suddenly getting Out of Memory. We're not expecting this to go out of memory on a 3GB memory CPU

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/18486164/129851202-c208e7aa-250c-49fc-bb3d-1712f47cf77c.png">

This behaviour occured after using react-timezone-select with react-transpile-modules

```
const withTM = require('next-transpile-modules')(['react-timezone-select']);
````

We've also tried resolveSymlinks true after reading [issuecomment-719449598](https://github.com/vercel/next.js/issues/7929#issuecomment-719449598), but even after that, the build is failing
```
const withTM = require('next-transpile-modules')(['react-timezone-select'], {
  resolveSymlinks: true
});
```

**Expected behavior**
The build should not fail

**Setup**
- Next.js version: 10.0.6
- `next-transpile-modules` version: 7.3.0
- Node.js version: 12
- `npm`/`yarn` version: 
- Operating System: linux
- Webpack 4 or 5: 5

**Comment by LukasBombach** [comment]
This may be related

https://github.com/changesets/changesets/issues/302#issuecomment-604723083
