### ISSUE TITLE
@babylonjs/inspector cannot be transpiled

### ISSUE THREAD

**Issue by saidmoya12** [martpie/next-transpile-modules#231]
**Are you trying to transpile a local package or an npm package?**
@babylonjs/inspector

**Describe the bug**
I can transpile the **@babylon/** modules except **@babylonjs/inspector**

**To Reproduce**
```js
///next.config.js
const withTM = require("next-transpile-modules")(
	[
		"@babylonjs/core",
		"@babylonjs/gui",
		"@babylonjs/loaders",
		"@babylonjs/inspector", //just this module
		"react-babylonjs",
	],
	{ debug: true }
);
```

**Setup**

- Next.js version:                              **11.1.0**
- `next-transpile-modules` version: **8.0.0**
- Node.js version:                            **14.16.1**
- `npm`/`yarn` version:                    **1.22.10**
- Operating System:                        **Windows 10**
- Webpack 4 or 5:                           **Webpack 5**

**Throw the next error**
```sh
error - ./node_modules/@babylonjs/inspector/babylon.inspector.bundle.max.js
TypeError: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "BooleanLiteral"
```

Someone can help me to solve this issue?

Thanks.

**Comment by martpie** [comment]
Can you paste the whole debug log please ? 🙏
