### ISSUE TITLE
SWC

### ISSUE THREAD

**Issue by martpie** [martpie/next-transpile-modules#237]
It looks like Next.js is experimenting with SWC. Investigate what it means for this plugin.

**Comment by karol-f** [comment]
I'm really waiting for that. Using SWC option on current Next canary versions, with:

```
experimental: {
    swcMinify: true,
    swcLoader: true
}
```

seems to work till next-transpile-module is aproached:

```
    |
101 |         delete<SRT, QPT extends DefaultQueryParametersType = undefined, BPT = undefined>(
    |               ^

error: Expected ',', got '< (jsx tag start)
```

so basically it does not treat this file as typescript one. Howewer typescript detection in `next-swc-loader` seems to work ok - https://github.com/vercel/next.js/blob/00431087d7ce2126bc819472cb3b71dbaefd46f7/packages/next/build/webpack/loaders/next-swc-loader.js#L108
