### ISSUE TITLE
Cannot resolve swiper@7 with next@10

### ISSUE THREAD

**Issue by neo** [martpie/next-transpile-modules#238]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

(nice! I like this haha)

**Are you trying to transpile a local package or an npm package?**
If an npm package, which one?

`swiper@7.0.8`

**Describe the bug**
A clear and concise description of what the bug is (don't forget the logs if applicable).

It says cannot resolve the package:

```
Module not found: Can't resolve 'swiper/react'
  1 | import { Pagination } from 'swiper';
> 2 | import { Swiper, SwiperSlide } from 'swiper/react';
  3 | 
  4 | import 'swiper/swiper.min.css';
  5 | import 'swiper/modules/pagination/pagination.min.css';
```

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):

Install `next@10` and `swiper@7`, and try to import from `swiper/react`

**Expected behavior**

It should import and run without problems

**Setup**

- Next.js version: `10.2.3`
- `next-transpile-modules` version: `7.3.0`
- Node.js version: `15.8.0`
- `npm`/`yarn` version: `1.22.11`
- Operating System: macOS `11.5.2`
- Webpack 4 or 5: `4`

**Additional context**

We used to do the following when swiper was at version 6:

```js
require('next-transpile-modules')([
  'dom7/dist/dom7.modular',
  'swiper/js/swiper.esm.js',
])
```

and now swiper is at version 7: https://swiperjs.com/migration-guide, I tried either of this and was not able to make it work:

```js
require('next-transpile-modules')(['dom7', 'swiper'])
```

or

```js
require('next-transpile-modules')(['dom7', 'swiper/react'])
```

Thank you!! :pray:

**Comment by martpie** [comment]
Can you paste here the whole log? (Enabling the `debug` flag would help too)

**Comment by martpie** [comment]
To fix the SSR issue, you will need to add `ssr-window` to ntm:

```
const withTM = require('next-transpile-modules')([
  'swiper',
  'ssr-window',
  'dom7',
]);
```

Regarding your app failing to import the component, the problem is in your setup ;) Webpack/Next.js is just saying it cannot find the library, but it's not related to `next-transpile-modules`.

**Comment by martpie** [comment]
Maybe something like this would help (forcing the module resolution manually with Webpack)

```js
const withTM = require("next-transpile-modules")(
  ["swiper", "ssr-window", "dom7"],
  {
    resolveSymlinks: false,
    debug: true,
  }
);
const path = require("path");

module.exports = withTM({
  webpack: (config, options) => {
    if (options.isServer) {
      config.externals = ["swiper", ...config.externals];
    }

    config.resolve.alias["swiper/react"] = path.resolve(
      __dirname,
      ".",
      "node_modules",
      "swiper",
      "react",
      "swiper-react.js"
    );
    config.resolve.alias["swiper"] = path.resolve(
      __dirname,
      ".",
      "node_modules",
      "swiper",
      "swiper-bundle.js"
    );

    return config;
  },
});

```

This is not a complete solution but this might be a step in the right direction (basically, tell Webpack where to find those modules)

**Comment by martpie** [comment]
What's the flag to enable esm support? I know it exists but I can't find it :(
