### ISSUE TITLE
Needs esmExternals: 'loose'

### ISSUE THREAD

**Issue by WillSquire** [martpie/next-transpile-modules#249]
Next.js v12.0 throws an error using this module unless I add `experimental: { esmExternals: 'loose' }` to the config. It doesn't mention this in your docs. It might be helpful if it's in the README as it mentions v12.0 support. Either that or documentation on loading the module with `import` rather than `require`.

**Comment by martpie** [comment]
Tests are green, please follow the issue template if there is a big with a particular setup. :)
