### ISSUE TITLE
Support next.config.mjs

### ISSUE THREAD

**Issue by slavb18** [martpie/next-transpile-modules#255]
- [X] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [X] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
If an npm package, which one?
next-auth (actual package does not matters)

**Describe the bug**
A clear and concise description of what the bug is (please include logs from your terminal with [debug](https://github.com/martpie/next-transpile-modules#withtmtranspilemodules--options) enabled).

Error in console:
```
[webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'fs'
```

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):

Create next.config.mjs
```
import withTmInitializer from 'next-transpile-modules';
import fs from 'fs';

const withTM = withTmInitializer([
  'next-auth',
]);


const nextConfig = {
  trailingSlash: false,
};


const tmConfig=withTM(nextConfig);
export default tmConfig;

```
then start app `npm run dev`

Example project https://github.com/slavb18/hello-world-app

**Expected behavior**
There should be no error  Caching failed for pack: Error: Can't resolve 'fs'

**Setup**

- Next.js version: 12.0.8
- `next-transpile-modules` version: 9.0.0
- Node.js version: 14.18.2
- `npm`/`yarn` version:8.1.1
- Operating System: Linux
- Webpack 4 or 5: Webpack 5

**Comment by martpie** [comment]
Hi! 👋

`.mjs` is now supported for Next.js configs? Did you try with a classic `next.config.js` just to see if it'd work?

**Comment by slavb18** [comment]
> Hi! wave
> 
> `.mjs` is now supported for Next.js configs? Did you try with a classic `next.config.js` just to see if it'd work?

classic next.config.js working:

```javascript
const withTM = require('next-transpile-modules')([
  'next-auth',
]);
const fs=require('fs');


const nextConfig = {
  trailingSlash: false,
};


module.exports=withTM(nextConfig);
```

but in my case mjs is required to import es6 module

**Comment by slavb18** [comment]
this issue can be fixed? or should I supply additional info ?

**Comment by martpie** [comment]
Sorry for the silence, I haven't had a look at it yet, but it definitely should be supported!
