### ISSUE TITLE
How it can support sourcemap for third party libarary installed node_modules

### ISSUE THREAD

**Issue by tianyingchun** [martpie/next-transpile-modules#256]
**Are you trying to transpile a local package or an npm package?**
 `@dimjs/utils`

**Describe the bug**
 how it can support sourcemap for third party libarary installed node_modules

i tried install thrid party libarary in node-modules in next app, import function from node_modules it seems it could not load source map file in chrome, e.g. i. have module file is-null.js & is-null.js.map the is-null.js.map indicates the source ts file.

but it can not display is-null.ts in chrome sources panel. is there missed some configuratins?

**To Reproduce**
see https://github.com/vercel/next.js/issues/34026

**Expected behavior**
see https://github.com/vercel/next.js/issues/34026

**Setup**

- Next.js version:
- `next-transpile-modules` version: latest
- Node.js version:
- `npm`/`yarn` version: npm 8
- Operating System:
- Webpack 4 or 5: 5

**Additional context**
next 12

**Comment by ronenempathy** [comment]
having the same issue . 

any workaround found around that?

**Comment by martpie** [comment]
cf. #291
