### ISSUE TITLE
Make packages that are transpiled nonManaged

### ISSUE THREAD

**Issue by paales** [martpie/next-transpile-modules#257]
**Is your feature request related to a problem? Please describe.**

We are using next-transpile-modules with great success and it is vital to our development workflow.

We are not only using it in a monorepo sense, but also use it when the packages are installed via node_modules. It works great, however it seems that webpack assumes that the packages in there are managed (managedPaths) and thus caches them hard.

We would like to to be able to make the path non-managed so the developer is able to fiddle around in those folders, make patches for those folders, etc., without breaking all caches.

Possibly related to: https://github.com/martpie/next-transpile-modules/issues/167 and thus https://github.com/webpack/webpack/pull/14509

**Describe the solution you'd like**

Be able or have as a standard that all transpiled folders can be changed and nextjs doesn't cache them indefintely.

**Alternatives considered**

Completely alternative setups would be welcome as well, but haven't found a solution yet.

**Comment by martpie** [comment]
Yes, this is a known issue I wanted to fix for quite some time:

https://github.com/martpie/next-transpile-modules/blob/c5f548e9adafdc9c5afb8a97f15a92f92bdcb266/src/next-transpile-modules.js#L179-L183

I was waiting for Webpack to implement Globs or non-managed paths which I believe they did a couple of months ago.

I don't have much time to do it myself. so a PR would be very appreciated :) I can help if needed.
