### ISSUE TITLE
An error occurred when "next build" with docker 

### ISSUE THREAD

**Issue by yuuk** [martpie/next-transpile-modules#258]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
local package

**Describe the bug**
I've clone the next monorepo demo https://github.com/martpie/monorepo-typescript-next-the-sane-way in my local machine(windows 10). Then I run `next build`, everything is ok！

![Snipaste_2022-02-25_20-33-14](https://user-images.githubusercontent.com/9426456/155718874-2008fc18-5bb2-491b-933b-194821e7a5dc.jpg)

But when I  do the same thing with docker, there was an error.
![Snipaste_2022-02-25_20-35-29](https://user-images.githubusercontent.com/9426456/155719176-3d6f9964-41c7-4959-a5f3-a33f602425bf.jpg)

The dockerfile config:
```
FROM node:12.22.0-alpine as builder
WORKDIR /
COPY package.json .
COPY yarn.lock .
RUN yarn install
COPY . .
EXPOSE 80
RUN yarn build:app
```

The root package.json: 
```
{
  "name": "monorepo-typescript-next-the-sane-way",
  "private": true,
  "workspaces": [
    "shared",
    "website"
  ],
  "scripts": {
    "build:app": "yarn --cwd=website build"  // Just and the script for dockerfile
  }
}

```

**To Reproduce**
Here is a repo i've created to reproduce the problem.
https://github.com/yuuk/monorepo-typescript-next-the-sane-way-with-docker

**Expected behavior**
Transpile modules without errors

**Setup**

- Next.js version: 12.0.1
- `next-transpile-modules` version: 9.0.0
- Node.js version: 12.22.0
- `npm`/`yarn` version: 1.22.10
- Operating System:  docker 
- Webpack 4 or 5: 5

**Comment by martpie** [comment]
Hi there! 

What you usually want to do with Docker is not to build your app with Docker unless you use multi-layer images. Otherwise you may end up with dev artifacts in your final docker image (node_modules, dev deps, not transpiled source code, etc).

My main advice is to build your app on your CI, then copy the Next.js build to your docker image.

**Comment by gndelia** [comment]
Having the same issue here, building in docker throws an error about not finding a local package that's installed as a dependency

**Comment by ErlanBelekov** [comment]
+1

**Comment by martpie** [comment]
Have you applied what I recommended here in my message above?

> What you usually want to do with Docker is not to build your app with Docker unless you use multi-layer images. Otherwise you may end up with dev artifacts in your final docker image (node_modules, dev deps, not transpiled source code, etc).

**Comment by andrussik** [comment]
Seems like symlinks are unstable with docker. I had strange situation where it worked locally, but got same error in pipeline during deployment.

You can fix it by copying your directory to node_modules before build:
COPY shared node_modules/shared
RUN yarn build:app

**Comment by martpie** [comment]
I would definitely recommend installing your deps before then copying them, rather than installing them from your Dockerfile.

Yes, it is less "the Docker way", but you'll save yourselves the hundreds of hours I spent trying to make our work.

**Comment by thara-3201** [comment]
is there any solution to it?

I'm facing an increase in deployment time significantly after using this module, has anyone faced this issue too?

**Comment by martpie** [comment]
> is there any solution to it?
> 
> I'm facing an increase in deployment time significantly after using this module, has anyone faced this issue too?

Where are you building your app? From your CI or from Docker? If Docker, try running the build on CI instead.
