### ISSUE TITLE
[question] SassError: @import "path" - Can't find stylesheet to import

### ISSUE THREAD

**Issue by xr0master** [martpie/next-transpile-modules#259]
Hi guys. Stumbled upon this project by accident and it's amazing!
Unfortunately, I can not solve the issue with sass `@import` in the transpile module. I will be grateful for any hint.
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/8962340/159170513-6985abf5-0a18-42f5-97fa-6aee83fd6e59.png">

**Comment by martpie** [comment]
please follow the issue template, otherwise it's hard to help you
