### ISSUE TITLE
[Question] Alternatives to "duplicated dependencies" issue

### ISSUE THREAD

**Issue by kylemh** [martpie/next-transpile-modules#260]
I've read [this part of the README](https://github.com/martpie/next-transpile-modules#i-have-trouble-with-duplicated-dependencies-or-the-invalid-hook-call-error-in-react) and the various related issues around monorepos...

I just want to make sure that... in executing on a [similarly shaped repository](https://github.com/vercel/turborepo/tree/main/examples/with-pnpm), my only options are:
- The previously linked README instructions
- Move relevant dependencies (react, styled-components) to the root of the monorepo.

In sounds like I should move deps to the root for simplicity, and hope none of my monorepo applications use a different version of `styled-components` or `react` in the future.

**Comment by martpie** [comment]
The goal is not to declare your deps at the root but to install them at the root via Yarn or NPM workspaces.

Does this monorepo example help? https://github.com/martpie/monorepo-typescript-next-the-sane-way

**Comment by kylemh** [comment]
I use `pnpm`. Does this mean I'd need to use `shamelessly-hoist`?

**Comment by martpie** [comment]
I've never used this feature of pnpm, but this work :) https://pnpm.io/workspaces

**Comment by kylemh** [comment]
I'm having a helluva time trying to get my monorepo working, but trying to create a minimum reproduction leads to everything working 😭 

Regardless, I don't think my issue has anything to do with `next-transpile-modules`.

In the minimum viable reproduction, there still exists `react` in both the package's `node_modules` _and_ the app's `node_modules`, but it seems to be correctly resolving from the app instead of `../../packages/ui/node_modules`, but I'm guessing pnpm's symlinks are behaving differently between my company's repo and the minimum repro attempt.
