### ISSUE TITLE
Question - Why is this package still needed when Nextjs 12 supports ES Modules?

### ISSUE THREAD

**Issue by jeremytenjo** [martpie/next-transpile-modules#265]
Nextjs 12 supposedly supports ES Modules, why does it still fail when building a Nextjs app with NPM packages that are ES modules?

![image](https://user-images.githubusercontent.com/25231946/173568089-60efdbbd-941f-4e5d-b701-c51d55134a8e.png)

**Comment by martpie** [comment]
Because Next.js support for ES Modules is light, and does not support advanced usecases like importing CSS from `node_modules`, or advanced monorepos setup.

If you just plan on using ES Modules from `npm`, Next.js built-in support should serve you well :)

**Comment by jeremytenjo** [comment]
Thanks @martpie for the reason, makes sense👍

For people interested the Nextjs team has an open RFC to fix this issue.

https://github.com/vercel/next.js/discussions/27953
