### ISSUE TITLE
Support SWC Loader

### ISSUE THREAD

**Issue by ScriptedAlchemy** [martpie/next-transpile-modules#266]
**Is your feature request related to a problem? Please describe.**
If i disable babel (delete the babel config) ill get "no loader for syntax" errors on my JSX in a monorepo

**Describe the solution you'd like**
Looking at the source, it seems theres only babel support. 
Ideally if we see the swc-loader is in the config.module.rules, we switch over to SWC and pass along the issuer, includes modifications

**Describe alternatives you've considered**
mutating webpack config manually, doing what you do but search for swc and patch the options 

**Additional context**
None

**Comment by martpie** [comment]
Is it actually possible to use SWC without Babel? I thought it went though it

**Comment by ScriptedAlchemy** [comment]
My bad it was my mistake. I forgot to add this

```js
    if (typeof nextConfig.webpack === "function") {
      return nextConfig.webpack(config, options);
    }
```

So half the configs were not being applied. 
Yeah i was sure ive made this work before, anyways ill close it - user error!
