### ISSUE TITLE
Will it support stylus in feature?

### ISSUE THREAD

**Issue by Creabine** [martpie/next-transpile-modules#268]
**Describe the solution you'd like**

Now this amazing plugin supports translation of all extensions supported by Next.js: .js, .jsx, .ts, .tsx, .mjs, .css, .scss and .sass, but sadly I use stylus, can you support that? 

Or is there any other plugin that can do this?

Thank you.

**Comment by martpie** [comment]
Please follow the issue issue template to get support.
