### ISSUE TITLE
Consider allowing a regex to be passed instead of an array of package names.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [martpie/next-transpile-modules#27]
So, in place of
```js
withTranspileModules({
  transpileModules: ['@org/foo', '@org/bar', '@org/baz'],
});
```
the user could do
```js
withTranspileModules({
  transpileModules: /^@org\/.+$/,
});
```
It'd decrease trouble getting the names of packages to be transpiled (wouldn't have to update `next.config.js` every time a new package from the monorepo is added or removed, wouldn't have to write a script to get the names to get around that) and end up creating a leaner regex (`includes` would just be `/^@org\/.+$/` instead of `[/@org/foo(?!.*node_modules)/, /@org/bar(?!.*node_modules)/, /@org/baz(?!.*node_modules)/]`)

**Comment by martpie** [comment]
You can just 

```
withTranspileModules({
  transpileModules: ['@org'],
});
```

**Comment by wtgtybhertgeghgtwtg** [comment]
While that does work, I couldn't find it in the documentation and it felt more like a serendipitous bug than anything.  If it's intended behavior, I'll close and use that.  Thank you.

**Comment by martpie** [comment]
Scoped packages are no diffferent than classic packages, they are just grouped into a single directory.

Regarding the "is it a bug or a feature?", some devs before reported that they just wanted to transpile specific scoped packages, so you know, I guess everyone has their usecase, preferences and setups.
