### ISSUE TITLE
Is it possible to "build" (or export) a transpiled Next.js module?

### ISSUE THREAD

**Issue by altechzilla** [martpie/next-transpile-modules#270]
I'm build a private NPM package that I'd like to use on certain projects, but I want the published version to only have a `dist` type folder where the compiled source is. Without having to include all the source files.

The module is using a lot of Next.js, and it's basically a way to share code between different projects. Any ideas on how to export a module like that which can still leverage things like the Next.js hooks (router, etc.)? 

Is that something specific to next-transpile-modules, or could it be done differently? Thanks a lot in advance!

**Comment by martpie** [comment]
Hello, sorry, i am not sure how it is related to `next-transpile-modules`. You basically just want to build an npm package, now depending on your build output (esm or commonjs), you may need ntm or not.

If you output commonjs, then just import your package as any other package.

**Comment by altechzilla** [comment]
Hey @martpie , thank you and my apologies if it's unrelated to the repo itself. I wasn't sure where to start and thought that based on the setup I currently have a good starting point would be ntm. 

What would you suggest between `esm` and `commonjs` if the goal was to keep the core project the same and only compile the npm package?

I'll check in on the Vercel Discord, thanks a lot!

**Comment by martpie** [comment]
To write a package, if you want to write TypeScript, you could use [tsdx](https://www.npmjs.com/package/tsdx), otherwise, if you want something more low-level and faster, [ESBuild ](https://esbuild.github.io/) is a nice choice too.

I am not sure how it is possible to re-use Next's internals though, but it should be do-able.

**Comment by martpie** [comment]
Regarding output, this is a delicate choice. ESM is the modern way, but not all tooling respects it well (that's why NTM exists), commonjs is safer, but older too.

**Comment by martpie** [comment]
Last but not least, Next.js supports ESM, but only "kinda", cf. https://github.com/martpie/next-transpile-modules/issues/265

**Comment by altechzilla** [comment]
Thanks a lot @martpie , really appreciated!

**Comment by altechzilla** [comment]
Hey @martpie , I followed your advice and started using ESBuild with ESM modules. Everything works, great, however it looks like every time the dist gets rebuilt, Next reloads the entire app. Is there any way to enable hot reload so that it only updates whatever component changes, similar to how it does for the app itself? Thank you!

**Comment by martpie** [comment]
ESBuild? With Next.js? O_o'

**Comment by altechzilla** [comment]
Yup! Using it to compile the modules and then loading the dist into the projects that use the shared library. It works flawlessly. But fast refresh breaks, so I'm wondering if there's a better way to do it using next-transpile where it references the source rather than the dist while in dev mode (i.e. if the module is npm linked)?

**Comment by altechzilla** [comment]
Ended up using a custom next.config.js plugin that leverages the transpiled components while in dev mode. Then, it exports the default as a bundle via a TSUP + Turbopack config. Best of both worlds - for DX while building and for the final build when delivering the final packages.
