### ISSUE TITLE
After using `withTM`, get `CSS Modules cannot be imported from within node_modules.` when importing css module from local folder

### ISSUE THREAD

**Issue by zh3ngyuan** [martpie/next-transpile-modules#275]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

#### repo for reproducing: https://github.com/ALexander4295502/next-scss-module

**Are you trying to transpile a local package or an npm package?**
npm package, `@heartlandone/vega-react`

**Describe the bug**
I have a package `@heartlandone/vega-react` that needs to be used in my next app, hence I use `next-transpile-modules` to transpile it so next won't complain it anymore. But after adding those lines in my `next.config.js`
```js
//@ts-check

// eslint-disable-next-line @typescript-eslint/no-var-requires
const withTM = require('next-transpile-modules')(['@heartlandone/vega-react']);
const { withNx } = require('@nrwl/next/plugins/with-nx');

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
};

module.exports = withTM(withNx(nextConfig));
```

my local css module `apps/next-scss-module/pages/index.module.scss` cannot be imported into my page `apps/next-scss-module/pages/index.tsx` anymore due to the error below:
```
Failed to compile
./pages/index.module.scss
CSS Modules cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-modules-npm
Location: pages/index.tsx
```

my next page content:
```tsx
import styles from './index.module.scss';

export function Index() {
  return (
    <div className={styles.page}>
    </div>
  );
}

export default Index;
```

**To Reproduce**
#### repo for reproducing: https://github.com/ALexander4295502/next-scss-module

Steps to reproduce the behavior (a reproduction is even better):
if you just comment out the line `import styles from './index.module.scss';` and remove the `styles` usage at Line 10 in `apps/next-scss-module/pages/index.tsx`, next can build my app without any error. but if you uncomment it out, the error will show up

**Expected behavior**
I should be able to import the scss module within my app without any error

**Setup**

- Next.js version: `12.2.5`
- `next-transpile-modules` version: '9.0.0'
- Node.js version: `v16.13.2`
- `yarn` version:  `1.22.17`
- Operating System: `macOS 12.5.1`
- Webpack 4 or 5: `5.74.0`

**Debug logs (optiona)**
```
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 99 ms (184 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
wait  - compiling / (client and server)...
(node:83018) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
error - ./pages/index.module.scss
CSS Modules cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-modules-npm
Location: pages/index.tsx
info  - automatically enabled Fast Refresh for 2 custom loaders
```

**Additional context**
I'm using nx for workspace management

repo for reproducing: https://github.com/ALexander4295502/next-scss-module

**Comment by ALexander4295502** [comment]
I found a similar issue reported https://github.com/vercel/next.js/discussions/15540, not sure why the latest version has this regression

**Comment by ALexander4295502** [comment]
After some research, I found a walk around to make `withNx` and `withTM` working harmoniously by using `next-composite-plugin` in the following way:
```js
//@ts-check

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { withNx } = require('@nrwl/next/plugins/with-nx');
const withPlugins = require('next-compose-plugins');
const withTM = require('next-transpile-modules')(['@heartlandone/vega-react']);

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
};

const plugins = [[withNx]];

module.exports = withTM(withPlugins([...plugins], nextConfig));
```

My guess here is `withTM` is modifying some of the css loader rule that `withNx` is updated, causing a local css import to be treated as import from `node_modules`, hence the issue happening.

I will leave it open for now as a placeholder for further discussion for a better solution.

**Comment by spaquis** [comment]
Hi @ALexander4295502 ,
I have the same problem with nx but your solution doesn't work for me, i only use nextTranslate in addition to your use case
The error stay "CSS Modules cannot be imported from within node_modules.", maybe i missing something ? 

```
const withTM = require('next-transpile-modules')(['react-dnd-scrolling']);

const plugins = [[withNx, nextTranslate]];

module.exports = withTM(withPlugins([...plugins], nextConfig));

```

Thanks

**Comment by ALexander4295502** [comment]
Hi @spaquis, sorry I cannot provide any insight on this, the only shoot I would suggest is checking the final output from `withTM` and make sure the css configuration created by `withNx` is persisted.
