### ISSUE TITLE
Doesn't transpile flow typed 

### ISSUE THREAD

**Issue by imranweb** [martpie/next-transpile-modules#28]
It doesn't support the flow typed syntax like:
import type { Node } from 'react';

**Comment by martpie** [comment]
Hello, 

I will need a little bit more explanations than that, can you provide a reproduction or something?

**Comment by imranweb** [comment]
I have mono repo setup:
-root:
 -- packages:
 --- app1
 --- app2
 --- shared


I am sharing "shared" package inside the "app1" as dependency.
like:
"dependencies": {
    "next": "^8.0.3",
    "next-transpile-modules": "^2.2.0",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    **"shared": "file:../shared"**
  },

When I use the "shared/Button" component inside **app1**, it throws compilation errors because its not transpiling the Flow-typed code in **shared** app.

**Comment by martpie** [comment]
I need to see your setup somehow, otherwise I can't reproduce, so I won't be able to help.

Can you provide a minimal reproduction of the problem? (on GitHub for example)

**Comment by imranweb** [comment]
Github: https://github.com/imranweb/nextjs-monorepor
Steps:
- Go to/packages/shared and run **yarn install** 
- Go to /packages/app1 and run **yarn install**
- Go to /packages/app1 and run **yarn dev**

You should see flow-typed syntax error.

**Comment by martpie** [comment]
In `app1`, rename `.babelrc` to `babel.config.js`, then start again

https://github.com/martpie/next-transpile-modules#i-have-trouble-making-it-work-with-nextjs-7

**Comment by martpie** [comment]
Did it work?

**Comment by imranweb** [comment]
Thank you so much.
It worked well.
