### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by Evanion** [martpie/next-transpile-modules#285]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [x] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
Local Turborepo package.

**Describe the bug**
When running `next build` in CI pipeline, it [throws an error](https://app.warp.dev/block/QTtMEumacG8u4sSSTpUd0R).
I'm also able to replicate this locally.

We are using [mui](https://mui.com) as the basis of our UI library, so we don't have any css files in our project as everything is styled components

**To Reproduce**
Steps to reproduce the behavior (a reproduction is even better):
I have no idea, this first appeared on our GH Actions CI pipeline.

**Expected behavior**
next build to complete correctly

**Setup**

- Next.js version: 13 & 12
- `next-transpile-modules` version: 10 & 9
- Node.js version: 18
- `npm`/`yarn` version: yarn 1.22 & 1.18
- Operating System: GH ubuntu-latest & MacOS 13
- Webpack 4 or 5: what ever is default for respective next version

* @ms/ui is an internal package to the monorepo, it's basically a library of components that wrap MUI components.
* next config included below

**Debug logs (optional)**
https://app.warp.dev/block/QTtMEumacG8u4sSSTpUd0R

**Additional context**

I have tried:
* Downgrade next to v12 (and ntm to v9)
* removed babel file (only used for formatjs string extraction related to react-intl)
* removed all experimental flags in next config

`next.config.js`
```js
const packageJson = require('./package.json')

const internalPackages = Object.keys(packageJson.dependencies).filter((it) =>
  it.startsWith('@ms/'),
)
const withTM = require('next-transpile-modules')(internalPackages, {
  debug: true,
})

module.exports = withTM({
  i18n: {
    locales: ['en_US', 'sv_SE'],
    defaultLocale: 'sv_SE',
  },
  poweredByHeader: false,
  reactStrictMode: true,
  swcMinify: true,
})

```

The error occurs in code relating to the webpack css loader as far as I can see:
```ts
if (nextCssLoader) {
  nextCssLoader.issuer.or = nextCssLoader.issuer.and ? nextCssLoader.issuer.and.concat(matcher) : matcher;
  delete nextCssLoader.issuer.not;             // ^ error occurs here
  delete nextCssLoader.issuer.and;
} else {
  console.warn('next-transpile-modules - could not find default CSS rule, CSS imports may not work');
}
```

**Comment by martpie** [comment]
Hello 👋

Are you using the new `app/` dir feature?

**Comment by Evanion** [comment]
No, the `next.config.js` in the post doesn't contain the config for it.
We would like to use the app dir, but it's borked when running Docker for some reason. Waiting for a response from vercel on that.

**Comment by Evanion** [comment]
I solved this by using the new built in `experimental.transpilePackage` config in next@13
