### ISSUE TITLE
Transpile modules not from node_modules

### ISSUE THREAD

**Issue by jim-king-2000** [martpie/next-transpile-modules#31]
**Is your feature request related to a problem? Please describe.**
Yes, it is related to a real problem. I'm building a test project for a ES6 module which uses Nextjs. So the ES6 module is imported by `import es6_module from '../../'`. However, it still needs to be transpiled although it is not in "node_modules".

**Describe the solution you'd like**
Transpile module from any path, `transpileModules: [ '../../' ]`.

**Describe alternatives you've considered**
It seems there is no alternative.

**Additional context**
None.

**Comment by martpie** [comment]
This plugin aims to transpile only modules in `node_modules`.

If you have a local package that you need to transpile, I encourage you to `npm i ../../your-package` in your Next.js directory and then use `next-transpile-modules`. You can also use Yarn workspaces to solve this problem.

This is for best practices, your Next.js app should not have a dependency your package.json does't know aboutt.

**Comment by martpie** [comment]
Some useful links:

- https://github.com/zeit/next.js/tree/canary/examples/with-yarn-workspaces
- https://github.com/martpie/monorepo-typescript-next-the-sane-way

**Comment by jim-king-2000** [comment]
I'll try `npm I ../../your-package` ASAP. Thanks.

**Comment by jim-king-2000** [comment]
I uses `npm i ../` and it works. Thank you, @martpie .
