### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by zimv** [martpie/next-transpile-modules#32]
hello~
Thanks for the plugin. I used to think that the `next-babel-loader` uses `exclude` to exclude `node_modules`. I did not know why the code in `node_modules` can't be imported until I saw the `webpack.externals` in your code. Now I think there's no need to push a new `defaultLoaders`, which is repetitive. You may want to delete it.
https://github.com/martpie/next-transpile-modules/blob/master/index.js#L65

**Comment by martpie** [comment]
Thanks for the suggestion, I may need to have a look into it indeed :)

**Comment by zimv** [comment]
I'm so sorry. I have a different usage scenarios. I only want to exclude some package of  `node_modules` from `externals`.I don't need the `next-babel-loader`.You are right.

**Comment by zimv** [comment]
hello~
I  new `defaultLoader`
