### ISSUE TITLE
Test cases not transpiling using Jest and Enzyme

### ISSUE THREAD

**Issue by imranweb** [martpie/next-transpile-modules#33]
I have monorepo setup. Please check this thread 
https://github.com/martpie/next-transpile-modules/issues/28#issuecomment-478483580

This is my package structure
- app
  -- components
  -- **babel.config.js**
  -- **next.config.js**
- server.js
- package.json
- config
  -- jest.config.js
  -- jest.setup.js

Please note babel.config.js and next.config.js are inside the /app directory.
It works well when I run the app but it failed while running the test cases.
When I copy the babel.config.js from /app to /root level then test cases works well.

Is there any way I can have only one babel.config.js and make both app and test cases works?

**Comment by martpie** [comment]
This goes a little bit beyond the scope of this package so I am going to close this.

I can give you a few hints though.

Having a look at your file structure, assuming `server.js` is just a classic Express serving Next.js, `babel.config.js` and `next.config.js` should then be at the root of your folder, and not in `app/`.

If you don't want to keep all the config files in the root folder (I think it does not matter), then you'll have to tweak Jest to pick the right `babel.config.js` located in `../app`.

Good luck!
