### ISSUE TITLE
Setup instructions for Create React App

### ISSUE THREAD

**Issue by lalicari** [martpie/next-transpile-modules#34]
Does this work with Create React App Typescript? If so, are there extra instructions needed for setup? Sorry if this is not the right place to ask this, still a newb.

Stumbled here from [this](https://github.com/OfficeDev/office-ui-fabric-react/issues/5236) thread. App uses es6 modules and ts, but the problem is that my tests also written in ts which use ts-jest need to be transpiled to use es5 since node doesn't support es6. I followed the ts instructions you have, but I'm not seeing the any change in the way my tests get run.

**Comment by martpie** [comment]
This plugin is specifically for Next.js and has nothing to do with CRA.

For examples, see:

- https://github.com/zeit/next.js/tree/canary/examples/with-yarn-workspaces
- https://github.com/martpie/monorepo-typescript-next-the-sane-way
