### ISSUE TITLE
npmjs repo is not @2.3.1

### ISSUE THREAD

**Issue by ikawka** [martpie/next-transpile-modules#40]
Hi, seems like npm repository is not updated?

**Comment by martpie** [comment]
It is? https://www.npmjs.com/package/next-transpile-modules

**Comment by martpie** [comment]
If you're talking about https://www.npmjs.com/package/next-plugin-transpile-modules, then just switch to `next-transpile-modules`, I renamed the module

**Comment by ikawka** [comment]
oh... thanks!
