### ISSUE TITLE
Problem when transpiling emotion

### ISSUE THREAD

**Issue by laidinidis** [martpie/next-transpile-modules#42]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Describe the bug**
I use monorepo with yarn workspaces. I have a Next.js app witch uses emotion and works fine. I also have ui components in separate package witch also uses emotion and works fine (in storybook). The problem is when I import a component from ui to the app it fails to transpile the css prop but when I use the [JSX Pragma](https://emotion.sh/docs/css-prop#jsx-pragma) it works fine. In both projects I use @emotion/babel-preset-css-prop. 

**To Reproduce**
- Create a monorepo with yarn workspaces
- Create a Next.js app in `packages` folder
- Add `next-transpile-modules` to the configuration
- Create a component in `packages/ui` folder and use `css` prop from `@emotion/core ` to style the component
- Import and use the component in Next.js app
- Add `@emotion/babel-preset-css-prop` to both projects

**Expected behavior**
The css prop should not get transpiled (I get `css="[object Object]"`) but when I add `/** @jsx jsx */ ` to the component everything works

**Setup**

- Next.js version: 8.1.0
- `next-transpile-modules` version: 2.3.1
- Node.js version: 12.3.1
- `npm` version: 6.9.0
- `yarn` version: 1.16.0
- Operating System: Windows 10

**Comment by martpie** [comment]
I used emotion and the css prop on projects using `next-transpile-modules` without any troube.

My Next.js `babel.config.js`:

```
// const isDev = process.env.NODE_ENV !== 'production';

module.exports = (api) => {
  api.cache(true);

  const presets = [
    ['next/babel', { 'preset-env': { useBuiltIns: 'usage' } }],
    '@zeit/next-typescript/babel',
    '@emotion/babel-preset-css-prop'
  ];

  const plugins = [];

  return {
    presets,
    plugins
  };
};
```

it should work fine.

**Comment by martpie** [comment]
(if you can't manage to fix it, having a small repro would help debug this issue)

**Comment by laidinidis** [comment]
OK I fixed it. I think it wasn't picking up the babel config. I have a client and a server folder (custom server) and the babel config was in the root of this project. I moved it to the client folder (next to next.config.js file) an now it works! Thank you!

**Comment by martpie** [comment]
Happy you figured it out!
