### ISSUE TITLE
Support the ".mjs" file extension

### ISSUE THREAD

**Issue by PoffM** [martpie/next-transpile-modules#46]
**Is your feature request related to a problem? Please describe.**
A library I use provides a file with a ".mjs" extension, which is not transpiled by this library. Everything seems to work for me if I change the file matching regex from /\.+(js|jsx|ts|tsx)$/ to /\.+(mjs|js|jsx|ts|tsx)$/ 

**Describe the solution you'd like**
Add "mjs" to the list of matched file extensions.

**Describe alternatives you've considered**
I'm not sure of an alternative for this.

**Comment by martpie** [comment]
Quick question to understand the full scope of the issue: why is this package shipping `.mjs` and not CommonJS? Also, which package is it?

**Comment by PoffM** [comment]
Hello, thanks for the help!

There are 2 packages: kitsu and kitsu-core from https://github.com/wopian/kitsu/

It seems to ship both js and mjs for both packages, but mjs is loaded by default. Though I'm not familiar with the difference between the two extensions.

**Comment by PoffM** [comment]
For some reason this worked for me when running `next` but failed when I ran `next build`:
```
Creating an optimized production build ...

> Using external babel configuration
> Location: "C:\Users\Poffm\seqdb-ui\babel.config.js"
Failed to compile.

./util/serialize.ts
Attempted import error: 'kebab' is not exported from 'kitsu-core'.

```

Gonna close this issue because I now have no reason to think my suggested code change would fix my problem. My next best idea is to copy kitsu's dist files into my source directory so Next.js can transpile them itself.
