### ISSUE TITLE
Debugging transpiled packages from node_modules

### ISSUE THREAD

**Issue by walleXD** [martpie/next-transpile-modules#48]
Is it possible to debug the packages being transpile from node_modules. I'm using lerna for my monorepo and I'm importing code from my other packages. I haven't had much success trying to debug the transpiled node_modules in both chrome & vscode.

Any way to get around this?

Thanks a bunch!

**Comment by martpie** [comment]
Hello 👋 I don't understand the problem you are trying to solve, what do you mean by "debug code from node modules"?

**Comment by martpie** [comment]
poke poke? :)

**Comment by martpie** [comment]
Can't really help without additional details, feel free to provide them and I'll re-open
