### ISSUE TITLE
Import errors at development (with `now dev`)

### ISSUE THREAD

**Issue by cibulka** [martpie/next-transpile-modules#49]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

Are you trying to transpile a local package or an npm package?
===
Local package (as in made by me) - but as I got some `npm link` weirdness with `now dev`, I edit the code right inside `node_modules` folder and after I'm ready to commit a change, I paste the code to my proper local git repository and push. (oh well)

Describe the bug
===

With `now dev` I started to get inconsistent import errors with transpiled libraries. It seems like some sort of weird race condition, as it does not happen always (but quite often). Also none of this happen in production.

This is my next.config.js:

```
const path = require('path');

const withPlugins = require('next-compose-plugins');
const withSass = require('@zeit/next-sass');
const withTM = require('next-transpile-modules');

module.exports = withPlugins([
	[withTM, {
	    transpileModules: ['nest-components', 'nest-helpers', 'nest-localization'],
	}],
	withSass,
], {
	target: 'serverless',
	webpack(config) {
		config.resolve.alias['config'] = path.join(__dirname, 'config');
		config.resolve.alias['translations'] = path.join(__dirname, 'translations');
		return config;
	},
});
```

This is my "main" file at `nest-components`:

```
export * from './actions';
export * from './components';
export * from './layouts';
export * from './hoc';
export * from './types';

export { default as translations } from './translations';
export { default as middleware } from './middleware';
export { default as reducers } from './reducers';

import * as actionTypes  from './action-types';
export { actionTypes };
```

Problem 1 - sometimes not everything is imported
---

```
import * as NC from 'nest-components'; // just to console.log the situation
import { actionTypes } from 'nest-components';

const Component = props => {
    console.log(NC); // => empty module
    console.log(actionTypes); // => undefined
    return (<div>Component</div>);
};
```

Problem 2 - submodules are not mapped to Redux connect `dispatchToProps`
---

```
import * as NC from 'nest-components'; // just to console.log the situation
import { getPosts } from 'nest-components';
import { connect } from 'react-redux';

const Component = props => {
    console.log(NC); // => module with everything, including function getPosts
    console.log(getPosts); // => function getPosts
    console.log(props.getPosts); // => undefined;
    return (<div>Component</div>);
};

export default connect(() => ({}), { getPosts });
```

To Reproduce
===
If neccessary, I can try to recreate some simplified version of my case. 

Expected behavior
===
`import { X from 'linked-repo' }` should consistently import what it should. `mapDispatchToProps` should map the functions to component as expected.

Setup
===

- Next.js version:
- `next-transpile-modules` version:
- Node.js version:
- `npm` version:
- Operating System:

**Comment by martpie** [comment]
Hi!

Instead of `npm link` or editing the files in `node_modules`, did you try a more convetional way? 

- classic `npm install`: https://github.com/martpie/monorepo-typescript-next-the-sane-way
- yarn workspaces

**Comment by cibulka** [comment]
Very quick response, thank you!

I did not know about the option to define a NPM dependency as a local file (`file:<path>`), so I will definitely use that (way less weird than `npm link`). Thanks!

Unfortunately it does not solve the problem with import errors I've described above at all. :( Do you have any idea what might be causing them?

**Comment by cibulka** [comment]
`index.js:1 Warning: Text content did not match. Server: "Kontakt" Client: "contact"` - this warning would suggest that the weird behaviour sometimes happens in client only (not on server). 

Context: Warning above complains about the part of code where I use I18n functions. If localization strings are present (meaning all imports work as expected), translated string appears ("Kontakt"). If not, key of the translation appears as fallback ("contact").

**Comment by martpie** [comment]
I have never used `now dev`, I will investigate. Does it happen also in classic next dev mode `next dev`?

> Very quick response, thank you!

well you know, sometimes it takes 10 seconds, sometimes 2 weeks 😄

**Comment by cibulka** [comment]
`next dev` and `now dev` seem to produce similar (and similarly inconsistent results). This also happens from time to time:

```
import { * as NC } from 'nest-components'; // for testing only
import { translations } from 'nest-components';

console.log(NC); // module with "translations" => { translations: {...}, ..., __esModule: true }
console.log(translations); // undefined
```

**Comment by martpie** [comment]
Then it's good news, it's probably an issue with your setup or your consumed files. Would you be able to provide a small repro for me?

**Comment by cibulka** [comment]
Honestly it's quite hard to reproduce the full situation to an abstract repo. Would you be ok if I gave you access to private repos concerned? Could i DM you somewhere?

**Comment by martpie** [comment]
Sure, just send it to my mail address (cf. my profile)

**Comment by cibulka** [comment]
I think I found out my issue.

`data.js` ->
```
import { a } from 'transpiled-module';

const modifiedModule = { a, b: 'b value' };

export default modifiedModule;
```

`component.js` ->
```
import data from './data.js';

const Component = props => {
    console.log(data.a); // => undefined
    return <div>{data.a}</div>;
};
```

If I export the module at `data.js` as a function and call it in `component.js`, everything resolves as it should.

`data.js` ->
```
import { a } from 'transpiled-module';

export default () => {
     const modifiedModule = { a, b: 'b value' };
     return modifiedModule;
};
```

`component.js` ->
```
import c from './data.js';

const Component = props => {
    const { a } = getData();
    console.log(a); // => a has value
    return <div>{a}</div>;
};
```

This is probably intended behaviour which I just missed. Thanks!
