### ISSUE TITLE
Important improvement for error messages

### ISSUE THREAD

**Issue by graphan** [martpie/next-transpile-modules#51]
**Is your feature request related to a problem? Please describe.**

Error messages from transpiled modules are not pointing to the file and line where an error occurs.

<img width="913" alt="Screenshot 2019-09-22 at 12 48 54" src="https://user-images.githubusercontent.com/22321063/65386177-4bbb8b80-dd38-11e9-86b0-5e277ba69c51.png">

**Describe the solution you'd like**

The same error messages like in next.js project

<img width="924" alt="Screenshot 2019-09-22 at 12 54 48" src="https://user-images.githubusercontent.com/22321063/65386180-5a09a780-dd38-11e9-9d8b-f19b770de865.png">

**Describe alternatives you've considered**

Error messages pointing to the file and line where the problem occurs.

**Additional context**
A project with yarn workspaces.

**Comment by martpie** [comment]
Are you talking about dev mode or production build? Do you have source maps enabled? I am not sure this plugin is exactly responsible of this behavior, but I can investigate a little bit.

**Comment by martpie** [comment]
Closing this for now. This is most probably an issue with Next.js anyway.

Feel free to provide more information so I can re-open it.
