### ISSUE TITLE
exported interfaces

### ISSUE THREAD

**Issue by TrejGun** [martpie/next-transpile-modules#53]
I'm not sure if it is bug report or feature request, so i want just ask

lets say my module is written in ts an has 2 files

file1.ts
```js
export interface IDummy {
}
```

file2.ts
```
export {IDummy} from "./file1"
```

so as you know babel does not emit types and no d.ts file would be created so IDummy would be just erased and file2 would die with error 

```
~/src/file1.ts
Attempted import error: 'IDummy' is not exported from './file1'.
```

how would you manage this situation?

Please do not suggest to not export types :)

**Comment by martpie** [comment]
I had a similar problem a while back, but I don't have it anymore. I do not remember the exact solution, but this thread will probably help you :) 

https://github.com/babel/babel/issues/8361

I think one of the key is to use `import * as` instead of named imports.

**Comment by kachkaev** [comment]
@TrejGun see https://github.com/zeit/next.js/issues/7882, the problem is not specific to this plugin 😉

**Comment by martpie** [comment]
Thank you @kachkaev for reminding me the initial issue, I actually commented there and this solved it for me: https://github.com/zeit/next.js/issues/7882#issuecomment-510478723

**Comment by TrejGun** [comment]
thanks guys
