### ISSUE TITLE
parse5 "exports is not defined"

### ISSUE THREAD

**Issue by 06e387** [martpie/next-transpile-modules#55]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**
`parse5@latest`

**Describe the bug**
Something weird going on. Get the following error:

```
index.js:2178 Error was not caught ReferenceError: exports is not defined
    at Module../node_modules/parse5/lib/common/html.js (html.js:3)
```

Which points to this in `html.js:3`:

```
...
const NS = (exports.NAMESPACES = {
...
```

**To Reproduce**
```
      ...
      transpileModules: [
        'parse5',
      ],
      ...
```

**Expected behavior**
Transpiles nicely like other modules.

**Setup**

- Next.js version: `8.0.1`
- `next-transpile-modules` version: `2.3.1`
- Node.js version: `10.16.1`
- `npm`/`yarn` version: `npm@6.9.0`
- Operating System: `macOS 10.15.1`

**Additional context**
None.

**Comment by martpie** [comment]
Can you tell me if this issue still happens in v3?

I'll also test on my end.

**Comment by 06e387** [comment]
Hi @martpie, thanks for taking the time!

Tried `next-transpile-modules@3.0.1`, but looks like it somehow ended up having the opposite effect: the only other module we were successfully transpiling before (`next-i18next`) is now failing with the original issue we were trying to fix:

> SCRIPT1028: Expected identifier, string or number

which points to the rest/spread operator. I double checked by switching back to `next-transpile-modules@2.3.1` and it worked fine again.

**Comment by Sangdt** [comment]
Same issue when having the use-global-hook package in the config. The `export default useStore` statement breaks the builds but with next-transpile-modules@2.3.1 work fine.

**Comment by martpie** [comment]
Can you share a reproduction? It would help to identify the root of the problem
