### ISSUE TITLE
Can I transpile all modules in node_modules?

### ISSUE THREAD

**Issue by tingtingtinghuang** [martpie/next-transpile-modules#64]
**Is your feature request related to a problem? Please describe.**
I am trying to transpile all modules used in my project include node_modules for some reason.

**Describe the solution you'd like**
something like:
```
withTM = require('next-transpile-modules')('node_modules')
```

**Additional context**
Nextjs dose not transpile modules in node_modules by default, but I hope my project doesn't depend on node_modules after build. Is there another way to reach?

**Comment by martpie** [comment]
I strongly recommend to not do that, it would be terrible for build performances.

If you still want to do that (again, don't), you may be able to achieve it with `withTM = require('next-transpile-modules')(['(.*?)'])`.

Please be aware that it is not documented, I will not document it, and it may break in any version, including patches ;)

ps: really, don't.

**Comment by martpie** [comment]
ps: I would still be interested by why you want to do that if you can share that.

**Comment by TrySound** [comment]
By the way I found very useful the ability to transpile whole scope like `['@realdvisor']`. This way I can easily add new packages to monorepo and not edit next configs.

**Comment by martpie** [comment]
Could you share usecases of why you would like your whole node_modules to go through Babel?

**Comment by tingtingtinghuang** [comment]
Sorry for late reply. Thank you for your advices:)
I am aiming to support IE11, So trying to transpile node_modules. But now I need to think more carefully about it.
By now, I just add these code to let Webpack bundle node_modules.
```
    if (newConfig.externals) {
      newConfig.externals = newConfig.externals.map(external => {
        if (typeof external !== 'function') return external;
        return (ctx, req, cb) => {
          console.log(path.resolve(ctx, req));
          return [/node_modules/].find(include => (include.test(path.resolve(ctx, req))
            ? cb()
            : external(ctx, req, cb)));
        };
      });
    }
```

**Comment by martpie** [comment]
I’d recommend going through the `with-polyfills` example of Next.js rather than transpiling all modules, you’ll end up with a much saber build.
