### ISSUE TITLE
webpackbar not working

### ISSUE THREAD

**Issue by ramesh-yadav** [martpie/next-transpile-modules#65]
webpackbar plugin is not working with this new approach.

const withTm = (transpileModules = []) => (nextConfig = {}) => {

compilation is working but bars are not working.

**Comment by martpie** [comment]
how do you know it is related to this plugin? do you have a reproduction?

**Comment by martpie** [comment]
- https://github.com/zeit/next.js/issues/4016#issuecomment-471861486
- https://github.com/lucleray/next-progressbar is deprecated

Feel free to submit a fix if you'd like, but it's not something I will be spending time on :)

**Comment by ramesh-yadav** [comment]
because your ^2.0.0 version is working fine

**Comment by martpie** [comment]
My point is a lot of changes were made between 2.x and 3.x, so the plugin instantiation *might* have nothing to do with this.

Following the two links above, I do not intend to fix this, as Webpackbar will slow your build and is unrecommended by Next.js maintainers.

If you manage to identify the exact issue, feel free to open a PR :)
