### ISSUE TITLE
TypeError using transpileModules option 

### ISSUE THREAD

**Issue by bySabi** [martpie/next-transpile-modules#67]
When I use the `transpileModules`  option it returns the error:

```
[ info ]  waiting on http://localhost:3000 ...
TypeError: modules.map is not a function

```

This is the not working `next.config.js`  file:
```js
const withTM = require('next-transpile-modules');

module.exports = withTM({
  transpileModules: ['@mono/foo'],
});
```

But it's working this way ... 
```js
const withTM = require('next-transpile-modules')(['@mono/foo']);
```

And this is a minimal repo: https://github.com/bySabi/mono-next with:
 -    "next": "^9.2.1",
 -   "next-transpile-modules": "^3.0.2",

**Comment by TrySound** [comment]
@bySabi This is expected. It was the point of major release.
https://github.com/martpie/next-transpile-modules/releases/tag/3.0.0

**Comment by bySabi** [comment]
Ah .. ok ... I had not seen that.
Thanks.

**Comment by bySabi** [comment]
@TrySound  this is my first time with `next-transpile-modules`. Is it supposed to work in a local typecript module? My minimal repo is not working: https://github.com/bySabi/mono-next

**Comment by TrySound** [comment]
```
const withTM = require('next-transpile-modules')(['@mono/foo']);
module.exports = withTM({})
```

**Comment by martpie** [comment]
> Ah .. ok ... I had not seen that.

It is a good habit to always read the changelog when you see a major version change in one of your packages :) usually, major implies breaking changes.

> Is it supposed to work in a local typecript module?

Yes it is, you can see an example here -> https://github.com/martpie/next-transpile-modules/tree/master/src/__tests__/__apps__

**Comment by bySabi** [comment]
Thanks @martpie for answer. 
I never use `next-transpile-modules` before  and I have not found a complete example that includes the last `next` and `next-transpile-modules` along with local typescript modules.
I will check provided __apps__ test. 

Thanks @TrySound, now is working.
