### ISSUE TITLE
Can't import enum from index.d.ts in node_modules

### ISSUE THREAD

**Issue by nbamfordcirium** [martpie/next-transpile-modules#68]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**
npm package
If an npm package, which one?
@nivo/bar
**Describe the bug**
I'm importing an enum from @nivo/bar/index.d.ts, 
`import { ResponsiveBar, BarLayerType} from "@nivo/bar";`

Later, I use it:
`<ResponsiveBar
    indexBy="x"
    enableLabel={false}
    colors={[barColor]}
    borderRadius={2}
    axisLeft={{
      tickValues: 7
    }}
      layers={[BarLayerType.Axes]}
  />`

`next build` reports `Failed to compile.
./src/components/livetrafficgraph/livetrafficgraph.tsx
Attempted import error: 'BarLayerType' is not exported from '@nivo/bar'.`
**To Reproduce**
Installing @nivo/bar and attempting to use the exported enum will cause the problem.
**Expected behavior**
The enum is tranpiled and available to my transpiled code.
**Setup**

- Next.js version: 9.2.1
- `next-transpile-modules` version: 3.0.2
- Node.js version: 12.14.1
- `npm`/`yarn` version: yarn 1.21.1
- Operating System:
OS X Mojave
**Additional context**
`// next.config.js
const withTM = require('next-transpile-modules')(['@nivo/bar']); // pass the modules you would like to see transpiled

module.exports = withTM();`

**Comment by martpie** [comment]
That is an interesting case. I need to do some research, about exposing Enums in definition files, I’ve never seen this pattern before.

Did you try to use just a string instead?

**Comment by nbamfordcirium** [comment]
I did that to workaround the issue, although that makes VSCode (probably the tslint plugin) report an error because it doesn't see `string` as the correct type for the function signature, which wants that `BarLayerType`.
So I have to do it like `layers={["axes" as any]}`

Which is fine, it works, I would just like the type safety of using an enum for the usual reason-- if I accidentally type "axese" or something, I won't find out until runtime, whereas `BarLayerType.Axeses` gives me an error in VSCode right away.

I'm also interested in this because my company makes a component library in typescript and we supply `.d.ts` files. I was hoping we could leverage enums for NextJS apps, but it appears that might not be the case.

**Comment by martpie** [comment]
I find weird that the library expect an enum for this props instead of a string. 

I’d be tempted to say it is a problem of the library, but I will need to investigate this usecase, I may perfectly wrong.

**Comment by martpie** [comment]
(I also completely get the type safety argument, I’m a TS fanboy as well)

**Comment by nbamfordcirium** [comment]
Thanks for the response! I understand if it's just not possible, just thought I would make sure.

The library itself will take a string for that prop like I ended up using, but I think VSCode picks up the function signature out of the `index.d.ts` file and that typed signature uses the `BarLayerType` enum, so it complains and I have to use `as any`.

**Comment by martpie** [comment]
Does the build (TS compilation) fails as well?

**Comment by nbamfordcirium** [comment]
It does, in the same way:

```$ NODE_PATH='./src' next build
Creating an optimized production build  

Failed to compile.

./src/components/livetrafficgraph/livetrafficgraph.tsx
Attempted import error: 'BarLayerType' is not exported from '@nivo/bar'.

> Build error occurred
Error: > Build failed because of webpack errors
    at build (/Users/bamfordn/one-cirium-analytics/node_modules/next/dist/build/index.js:10:900)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by martpie** [comment]
The import/export type feature of TS 3.8 may be able to help with this issue
