### ISSUE TITLE
imported styled-jsx not working for SSR

### ISSUE THREAD

**Issue by fatlinesofcode** [martpie/next-transpile-modules#70]
Hi,
I've just updated to next 9.2 and v3 of the plugin.

I'm using a yarn-workspaces structure and I've noticed if I import a component with styled-jsx, the styles are not injected in the ssr. Client-side render works fine. Here's example : 

/site/TestPage.js

```
import TestStyle from 'shared/components/page/TestStyle'

const TestPage = ({data}) => (
  <div>
    <div className={"text"}>local jsx</div>
    <TestStyle/>
    <style jsx="">{`
      .text {
        background-color: red;
      }
    `}
    </style>
  </div>
)

export default TestPage
```

/shared/TestStyle.js
```
const TestStyle = ({data}) => (
  <div className={"TestStyle"}>
    import style
    {/*language=SCSS*/}
    <style jsx="">{`
      .TestStyle {
        background-color: green;
      }
    `}
    </style>
  </div>
)

export default TestStyle
```

next.config.js
```
const withTM = require('next-transpile-modules')(['shared']);
module.exports = withTM({
})
```
babel.config.js
```
module.exports = api => {
  api.cache(true)
  return {
    presets: [
      [
        'next/babel',

      ]
    ],
  }
}
```

SSR result
![Screen Shot 2020-02-26 at 3 48 15 pm](https://user-images.githubusercontent.com/505776/75312901-71ccf500-58af-11ea-9b25-3f9baa1c3e25.png)

CSR result
![Screen Shot 2020-02-26 at 3 48 23 pm](https://user-images.githubusercontent.com/505776/75312913-785b6c80-58af-11ea-8495-1e81d52f1258.png)

This used work fine with next 9.05 & modules v2

**Comment by martpie** [comment]
Thanks for the report, can you confirm if it was introduced by the Next.js or ‘next-transpile-modules‘ update? (‘next-transpile-modules‘ v2 should also work with 9.2 if you don't use the CSS features that shipped with it)

**Comment by martpie** [comment]
Btw, I am pretty sure your `babel.config.js` is useless and you can delete it safely :) 

But this is probably another issue

**Comment by fatlinesofcode** [comment]
hi @martpie thanks for the reply. You can ignore this, i got it working now. I deleted yarn.lock all node_modules and run upgrade-interactive again. Everything seems to working fine now.

**Comment by martpie** [comment]
Nuking `node_modules` + lock file is the new "have you tried to turn it off and on again"
