### ISSUE TITLE
Willing to accept a PR for Webpack 5

### ISSUE THREAD

**Issue by ScriptedAlchemy** [martpie/next-transpile-modules#72]
**Is your feature request related to a problem? Please describe.**
Webpack 5 changed its loader issuer context and schema. Thus this plugin will not work 

**Describe the solution you'd like**
Id like to upgrade the API to work with Webpack 5, of which I am a core contributor and actively been working on Webpack 5's core

**Describe alternatives you've considered**
Forking and distributing this project under my module-federation organization. 
module-federation is a flagship feature I implemented into Webpack 5

**Comment by ScriptedAlchemy** [comment]
I’m one of the webpack core  maintainers. So I know it’s release date. I’ve also already upgraded next to v5 in prep. I do understand keeping with next versions and understand where you are coming from. 

With that said, if I were doing most of the work and made it backwards compatible, would you work with me? I’d prefer not to fork and distribute another version. 

I’m using next with w5 to take advantage of module-federation, your plugin is one that I need to upgrade as I use it. Extending the offer to avoid having two copies out there. 

Your logic is sound. Next is on v4 right now, but I’m already deploying w5 versions. However transpile modules is one of the last in my stacks to update. 

If you’re not willing to accept a PR at this time. That’s fine, I can distribute a copy on NPM - but as the author of the project, it would save us both time. You know your code, and I was part of writing WP5 - together it would be less effort than apart :) 

I’m also willing to distribute and test it on my own production codebases ahead of time - if you’re willing to review some PRs. When you feel ready I can open a pr to this project

**Comment by martpie** [comment]
I need a bit more context before being able to give an answer :)

Are you saying the official Next.js Canary is using Webpack v5? Or a custom branch under `zeit/next.js`? Where can I see the `next` package in action with Webpack 5? 

I am totally willing to add support for Webpack v5 (under a flag most probably), but I just need a bit more information on your usecase, as I am watching Next.js releases quite closely, but did not see anything related to Webpack 5 (I may have missed something), and Webpack 5 is still in beta.

But I can totally imagine something like:

```
const withTm = require('next-transpile-modules')(['stuff', 'something-else'], {
  experimental: {
    webpack5: true
  }
});
```

**Comment by martpie** [comment]
ps: I am always open to PRs for all my packages/open-source projects ;)

**Comment by ScriptedAlchemy** [comment]
I upgraded it on a fork before approaching them. I’m now discussing refining and opening the pull request with experimental flags. Seeing as most of it is done. 

So it’s not official yet, but I did do it on my own and likely will get it open to next.js in the news week or so depending on some refinements and extra checks

**Comment by ScriptedAlchemy** [comment]
This is still a little rough. But it’s working, your plug is been tricky - tests pass but when I try it in yarn workspaces it fails and whines about missing loader. So I know something is a little borked. https://github.com/module-federation

**Comment by martpie** [comment]
Yarn is a bit tricky indeed, I should create integration tests for it.

**Comment by ScriptedAlchemy** [comment]
Zeit has started merging my PRs in so Webpack 5 will be compatible with it soon. You use a yarn resolution and install WP5 then next uses other hooks

**Comment by martpie** [comment]
I saw the PR for Webpack 5 indeed. I'll wait for a stable release before working actively on it. No need to waste efforts as long as it's not used by upstream.

**Comment by ScriptedAlchemy** [comment]
It’s in upstream - they merged in the first stages. It’s actively being worked on internally 

![image](https://user-images.githubusercontent.com/25274700/79525667-50b79380-8018-11ea-90d0-257c836e8f9e.jpeg)

**Comment by martpie** [comment]
They merged compatibility improvements, not a full Webpack 5 support yet ;)

Webpack 5 is still in Beta, and breaking changes can still appear on both Webpack and Next.js configuration side.

Hence the low incentive on working on this issue. When there will be a clear sign that Webpack 5 is stable, and that the next Next.js release will use Webpack 5, then it will become urgent, and I'll be able to work on this without fearing that something breaks in each Webpack release or Next.js Canary :]

**Comment by ScriptedAlchemy** [comment]
Booo okay. I’ll be more direct 


My company is blocked by transpile modules. I’ve got all the other pieces working and am a core contributor of webpack, so I know what’s not going to change and how little is left.

Can I open a PR and perhaps ask a question if I get stuck. Assuming I provide total backward compatibility just like I did for next.js I’d prefer not to fork and publish. Adds to OSS fragmentation. 

Will you click merge if I do all the work :)

**Comment by ScriptedAlchemy** [comment]
I’ve rewritten every webpack loader or plugin at the company. This is the last one. It’s more work to remove the plugin than to fix it on my end.

**Comment by martpie** [comment]
Well, I need to see the solution, but if it's backwards compatible and tests are passing, then let's merge it! 🚀

I will never be against PRs if they are not too controversial, I was just talking about my personal incentive on working on these to patch them.

I could also release this patch under a special tag ‘4.0.0-beta‘ or whatever).

Anyway, I will wait for your PR and we can start from there :)

**Comment by ScriptedAlchemy** [comment]
Perfect!

Thanks man. Pending the solution of course will impact mergability 

Sometimes oss is weird and others won’t take contributions, just wanted to clear the runway beforehand. 

I’ll see what I come up with and we can take it from there

**Comment by ScriptedAlchemy** [comment]
Ahh okay, this is pretty straight-forward to fix. Looks like we just need to update the issuer syntax, it only accepts regex now. 

https://github.com/zeit/next.js/pull/10885/files#diff-4ec59a55144129a45f46da71c0777df9

![image](https://user-images.githubusercontent.com/25274700/79813883-bb771080-8331-11ea-9cf3-17dc41f753f8.png)
