### ISSUE TITLE
Unable to load font files

### ISSUE THREAD

**Issue by arnaudpeich** [martpie/next-transpile-modules#78]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**
A local package

**Describe the bug**
When a SCSS file defines a font-face and loads a font file, that font is not correctly loaded.

**To Reproduce**

In `_app.tsx`:
```ts
import App from 'next/app'
import 'my-styleguide/stylesheets/reset.scss'
export default App
```

In `reset.scss`:
```scss
@font-face {
  font-family: 'MyFont';
  src: url('./webfonts/myfont.eot');
  // And then some woff, woff2 and ttf
}
```

In `next.config.js`:
```js
const withTM = require('next-transpile-modules')(['my-styleguide'])
const withFonts = require('next-fonts')
module.exports = withFonts(withTM()) // I tried the other way around too.
```

When I start the next dev server, I find a file named `.next/static/media/myfont.[hash].eot` that contains the following:
```js
module.exports = "/_next/static/chunks/fonts/myfont-[a-different-hash].eot";
```
The referenced file exists and contains the font. But the browser is trying to decode the file in `media/` as a font, not the one in `chunks/fonts` (I get a `console.warn`: 'Failed to decode downloaded font').

**Expected behavior**
I would like the font to be loaded correctly :)

**Setup**

- Next.js version: 9.3.1
- `next-transpile-modules` version: 3.1.0
- Node.js version: 13.7.0
- `npm`/`yarn` version: yarn 1.21.1
- Operating System: Mac OS 10.15.4

**Additional context**
This is a follow up of [this issue](https://github.com/zeit/next.js/issues/11372) that you helped resolve :)

It works fine when I use `@zeit/next-sass` but I'd like to use the built-in support.

**Comment by martpie** [comment]
Indeed, fonts are not supported, I have to check if they are supported by Next.js, if yes, it should be trivial to add support for them.

**Comment by arnaudpeich** [comment]
I just tried it and it seems like Next.js doesn't support it, even with the `next-fonts` plugin.

I did the test with exactly the same setup as above, but I moved the files inside the app and changed the import to `../stylesheets/reset.scss`: same error as before.

Seems to me it is not for this plugin to fix, so I'm closing this issue and I'll open one on the Next.js repo directly.

**Comment by arnaudpeich** [comment]
Oh wait, it _does_ work when I disable the `next-fonts` plugin.

**Comment by arnaudpeich** [comment]
And it works too when I load the font from my module... I reopened this too quickly, my bad.

So in conclusion everything works as one could dream without using next-scss or next-fonts! Great job on this plugin :)
