### ISSUE TITLE
Existing config functions are overwritten

### ISSUE THREAD

**Issue by davecardwell** [martpie/next-transpile-modules#82]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE

**Are you trying to transpile a local package or an npm package?**
N/A

**Describe the bug**
Next.js allows you to use a function for your existing config, however next-transpile-modules does not:

```js
module.exports = withTM((phase, { defaultConfig }) => {
  return {
    ...defaultConfig,
    
    webpack: ((config, { isServer }) => {
      // my webpack config changes

      return config;
    },
  };
});
```

In this example the existing config would be lost. I think it would be preferable to support the Next.js config as a function, however if that is not possible then an explicit note in the usage documents about using next-compose-plugins to support this case.

*However*, even using next-compose-plugins would not work in my example as next-transpile-modules overwrites any existing `config.webpack` and `config.webpackDevMiddleware`.

I believe next-transpile-modules should be updated to check if there are already existing `config.webpack` or `config.webpackDevMiddleware` functions and call them first, then work on the resulting config object.

My current workaround follows. next-transpile-modules would just need to do what my `withWebpackConfig` function does internally.

```js
const withWebpackConfig = (config) => {
  const tmWebpackFunc = config.webpack;

  config.webpack = (webpackConfig, options) => {
    webpackConfig = tmWebpackConfig(webpackConfig, options);

    // my webpack config changes

    return webpackConfig;
  };
};

module.exports = withPlugins(
  [withTM, withWebpackConfig],
  (_, { defaultConfig }) => {
    return {
      ...defaultConfig,

      // my Next.js config changes
    },
);
```

**To Reproduce**
See description.

**Expected behavior**
I expect the existing webpack config functions to be called.

**Setup**

- Next.js version: 9.3.5
- `next-transpile-modules` version: 3.2.0
- Node.js version: 13.13.0
- ~~`npm`~~/`yarn` version: 1.22.4
- Operating System: macOS 10.15.4

**Additional context**
N/A

**Comment by martpie** [comment]
You will probably be interested by this https://github.com/zeit/next.js/issues/11000#issuecomment-598178943

**Comment by davecardwell** [comment]
> You will probably be interested by this [zeit/next.js#11000 (comment)](https://github.com/zeit/next.js/issues/11000#issuecomment-598178943)

Ah yes, thank you. That would let me compose without having to add a dependency on next-compose-plugins.

It still wouldn’t help with the `config.webpack` clobbering though would it?

**Comment by martpie** [comment]
`next-transpile-modules` supports `config.webpack` composition:

https://github.com/martpie/next-transpile-modules/blob/0ab935c721a46190e045067ced5d5a8c4dbdcd02/src/next-transpile-modules.js#L141-L144

**Comment by martpie** [comment]
Unless I misunderstood what you meant

**Comment by davecardwell** [comment]
You’re right—looks like it was just a symptom of my trying to use the function form of nextConfig.

Now I moved the `withTM()` call to wrap the return inside that nextConfig function the webpack config is preserved.

Thanks for your help!

**Comment by switz** [comment]
So this works... in that if you put the webpack config _inside_ of the withTM call it works. But if you do it anywhere outside, it breaks it. Seems like it should ingest the existing config, rather than overwriting it, even if you don't put it inside of the `withTM` call itself.

**Comment by martpie** [comment]
This is unfortunately not doable https://github.com/vercel/next.js/issues/11000#issuecomment-598178943
