### ISSUE TITLE
Upgrading to 3.3.0 somehow brakes storyshots with "cannot find module @jest/globals"

### ISSUE THREAD

**Issue by reckter** [martpie/next-transpile-modules#84]
**Describe the bug**
When upgrading from `next-transpile-modules@3.2.0` to `next-transpile-modules@3.3.0` the storybook-storyshots jest setup brakes with `Cannot find module '@jest/globals' from 'storyshots.test.ts'`

The weird thing is, that it does not happen with the actual code changes made in 3.3.0 applied to 3.2.0. But it happens every time the installed package.json of next-transpile-modules says "3.3.0". 

I tested it by installing 3.2.0 (test work) and than manualy replacing in with "3.3.0" in the package.json in the node_modules folder. (test brake).

I installed 3.3.0 (test brake), and manualy replaced "3.3.0" in the package.json with "3.2.0". (test work)
Replacing "3.3.0" with "3.3.1"("3.4.0" also worked) seems to fix it, but I am unsure wether a new release will have the same effect.

I can not reproduce the same effect with other installed packages, that's why I am writing this here. (Edit: I managed to get the same results by replacing the version in "babel-jest" from "25.5.0"(brakes) to "25.2.4"(works). (again without actually installing a different version))

I know that this is quite a weird error, and I do not know what the underlying problem is, and if there even is one. This is more of an FYI, and it might help some lost googler (like myself a few hours ago).
l

**To Reproduce**
- storybook setup
- jest with a storyshots setup
- update next-transpiles-modules to 3.3.0
- run tests

**Setup**

- Next.js version: 9.3.2
- `next-transpile-modules` version: 3.3.0
- Node.js version: v12.8.1
- `npm`/`yarn` version: npm: 6.14.4
- Operating System: macOS

**Comment by reckter** [comment]
This of course was not related to this project at all.
I still have no idea what was going on, but removing an old dependency (@glidejs/glide), which happened to be mocked in these storyshots test did solve it.
Why installing a new version of this dependency caused this weird behavior is still beyond me. 

Thanks for this awesome module and have a nice day!

(And to the future Googler that finds this: If you ever figure it out, please leave a comment here, I am still curious!)

**Comment by martpie** [comment]
usually, a `rm -rf node_modules package-lock.json && npm ci` fixes 80% of the problems ;)

**Comment by reckter** [comment]
Yeah, that's always my first try :D
