### ISSUE TITLE
Compatibility with nextjs canary

### ISSUE THREAD

**Issue by jeantil** [martpie/next-transpile-modules#88]
**Is your feature request related to a problem? Please describe.**
Trying to upgrade an app using next-transpile-module@3.3.0 to use nextjs@9.4.5-canary.20 breaks `next dev` with the following error : 
```
TypeError: Cannot read property 'concat' of undefined
    at Object.webpack (/home/jean/dev/node_modules/next-transpile-modules/src/next-transpile-modules.js:102:73)
    at Object.webpack (/home/jean/dev/node_modules/@zeit/next-source-maps/index.js:34:29)
    at getBaseWebpackConfig (/home/jean/dev/node_modules/next/dist/build/webpack-config.js:115:372)
    at async Promise.all (index 1)
    at async HotReloader.start (/home/jean/dev/node_modules/next/dist/server/hot-reloader.js:14:2147)
    at async DevServer.prepare (/home/jean/dev/node_modules/next/dist/server/next-dev-server.js:11:378)
    at async /home/jean/dev/node_modules/next/dist/cli/next-dev.js:21:359
``` 

running ` NODE_OPTIONS='--inspect-brk' next dev     ` allowed me to the internal changes in cssloader config: 
```
> console.log(nextCssLoader.issuer)
undefined
v Object {and: Array(1), not: Array(1)}
 > and:Array(1) ["/home/jean/dev/www"]
 > not:Array(1) [/node_modules/]
```
**Describe the solution you'd like**

I would like the app to start normally :)

**Comment by jeantil** [comment]
The breakage was introduced by 
https://github.com/vercel/next.js/commit/1fc0aae5891644e6e3a719befb642d275472c537#diff-4ec59a55144129a45f46da71c0777df9

**Comment by martpie** [comment]
Does it work with the current stable version of Next.js?

**Comment by jeantil** [comment]
> Does it work with the current stable version of Next.js?

Yes it does, but it will immediately break with the next release, I thought it was worth a heads up.

**Comment by martpie** [comment]
Thanks, I'll have a look at what changed exactly in Next.js Webpack config :+1:

**Comment by martpie** [comment]
Thanks, I'll have a look at what changed exactly in Next.js Webpack config :+1:

**Comment by dan-wu39** [comment]
@martpie it looks like the css-loader might have changed
```
// line 102 in my node_modules
nextCssLoader.issuer.include = nextCssLoader.issuer.include.concat(includes);
```
The `issuer` object's keys changed from include/exclude to and/not

**Comment by migatech2015** [comment]
@dan-wu39 I've opened a pull request to fix the compatibility with nextjs 9.4.5. It works with my project that uses nextjs v9.4.5-canary.26.

**Comment by jeantil** [comment]
@martpie nextjs 9.5.0 has just been released

**Comment by martpie** [comment]
Thank you! I'll have a look asap

**Comment by martpie** [comment]
Looks like Next.js is burning right now, the package was never published and they rolled back the website 🙈

The WIP is there: #93, I have to add some tests for Webpack 5, and once the release will be official, I'll release it :)

**Comment by DScheglov** [comment]
So, @martpie 
Could you clarify, what I should we that? My build is broken right now

**Comment by martpie** [comment]
You should not update Next.js without making sure all your plugins are compatible with it ;)

The release is in progress, please give me some time

**Comment by DScheglov** [comment]
@martpie ) In development mode all dependencies are been updated automatically. So, it's only develop is broken. 
Well -- will fix version of `next` until your fix be issued

**Comment by martpie** [comment]
>  In development mode all dependencies are been updated automatically

well I sure hope you are using a lockfile, and `npm ci` when installing your dependencies ;)

4.0.0 is out :) https://github.com/martpie/next-transpile-modules/releases/tag/4.0.0

**Comment by jeantil** [comment]
Thanks for the quick update !

**Comment by luknl** [comment]
Hey, I just came across the same error as you @jeantil, when building our app on the Gitlab CI/CD pipeline.
`npm run build` works fine locally, but in a prod environnement, the pipeline shows this error and won't build.
What is strange is that it builded it fine 5 days ago, and now this error shows up, even though I didn't change anything.
Do you have any idea why, and what I should do to fix that? Perhaps upgrading this package, or/and the next one?
Here are my versions:
"next": "^9.4.4",
"next-transpile-modules": "^3.3.0",
"webpack": "^4.43.0"
Thank you!

**Comment by martpie** [comment]
Depends how you install your dependencies in your CI, if you install them with `npm install` it's normal because `"next": "^9.4.4",` will resolve to 9.5.0. And this is why you should always install your dependencies with `npm ci` or `yarn --frozen-lockfile` **so you only install the dependencies that are resolved in your lock file**.

**Comment by martpie** [comment]
I added a FAQ note about that: https://github.com/martpie/next-transpile-modules/blob/master/README.md#a-new-version-of-nextjs-is-availablei-just-setup-my-project-and-my-build-is-breaking-because-of-this-plugin

**Comment by dan-wu39** [comment]
Thanks @martpie , the importance of lockfiles is best learned through pain :)

**Comment by luknl** [comment]
Thank you @martpie, didn't knew about `npm ci`, will try that :)

**Comment by brotzky** [comment]
After following these steps i've run into a new issue with `webpack` not being found in `next-transpile-modules.js`

```
yarn run v1.22.4
$ next -p 5000
ready - started server on http://localhost:5000
Error: Cannot find module 'webpack'
Require stack:
- /Users/user/Code/fey/fey/node_modules/next-transpile-modules/src/next-transpile-modules.js
...
```

has anyone run into anything similar?

**Comment by martpie** [comment]
@brotzky please understand the inner problem ;)  you will be fine using the latest version of Next.js with the latest version of this plugin.

There is no need to fix the version of your dependencies: install your department via lockfile, not via package.json, so you can enjoy the latest Next.js features! https://github.com/martpie/next-transpile-modules/issues/88#issuecomment-666328343
