### ISSUE TITLE
Not working with styled-components

### ISSUE THREAD

**Issue by stijnvanderlaan** [martpie/next-transpile-modules#99]
**Describe the bug**
styled-components is not able to use a shared babel-plugin so classNames will interfear.

**To Reproduce**
Use styled-components inside a different package then the next app and import it:

```js
import Component from '@myapp/components/Component';
```

**Possible fix**
A fix for this problem is to be able to set the rootMode option to the next-babel-loader (maybe as a configuration option:
```js
config.module.rules.push({
  test: /\.+(js|jsx|mjs|ts|tsx)$/,
  use: {
    ...options.defaultLoaders.babel,
    options: {
      ...options.defaultLoaders.babel.options,
      rootMode: 'upward'
    }
  },
  include: includes
});
```
So alle packages are using the same babel config, which fixes the issue (testen locally by copying the source)

**Comment by martpie** [comment]
Please follow the issue template :)

**Comment by stijnvanderlaan** [comment]
I found out you could configure babel a different way, adding this fixes the problem for me:
```js
    babel: ({ babelConfig, options }) => {
      babelConfig.rootMode = 'upward'
      return babelConfig
    },
```

**Comment by florianmatz** [comment]
Sorry to re-open this issue, but any fix on that? I seem to have the same problem, when pulling ES Module from my component library, the generated classes missmatch vom SSR -> FE. 

Like the problem that is solved with [this](https://github.com/nblthree/nextjs-with-material-ui-and-styled-components/blob/master/pages/_document.js)

Unfortunately the document config does not consider transpiled modules. Can you maybe help me with that issue?

<img width="1002" alt="Bildschirmfoto 2020-09-06 um 13 00 50" src="https://user-images.githubusercontent.com/4760056/92324340-19866500-f041-11ea-8d66-2840744f8fcd.png">

NdNavigation is a custom component wrapping some Material UI stuff and is coming out of my custom library. The lib gets transpiled via your awesome plugin. Unfortunately it brings me back to the described error...
